"""Curated seed of Libertex MT5 Market CFDs.

Each row provides:
  symbol      -- canonical Libertex/Markowitz Lab symbol
  yf_symbol   -- ticker passed to yfinance
  tv_symbol   -- TradingView symbol (used by the MCP fallback)
  name        -- human-readable name
  category    -- stock | index | commodity | crypto | fx | etf
  currency    -- quote currency
  is_crypto   -- whether to fetch at weekly cadence

This file represents the bulk of the liquid universe Libertex offers
under the MT5 Market account type. The Chrome-MCP refresher
(libertex_parser.py) can extend / refresh this list at runtime.
"""

LIBERTEX_SEED = [
    # ---------- US LARGE-CAP STOCKS ----------
    ("AAPL", "AAPL", "NASDAQ:AAPL", "Apple Inc.", "stock", "USD", False),
    ("MSFT", "MSFT", "NASDAQ:MSFT", "Microsoft Corp.", "stock", "USD", False),
    ("GOOGL", "GOOGL", "NASDAQ:GOOGL", "Alphabet Inc. Class A", "stock", "USD", False),
    ("AMZN", "AMZN", "NASDAQ:AMZN", "Amazon.com Inc.", "stock", "USD", False),
    ("NVDA", "NVDA", "NASDAQ:NVDA", "NVIDIA Corp.", "stock", "USD", False),
    ("META", "META", "NASDAQ:META", "Meta Platforms Inc.", "stock", "USD", False),
    ("TSLA", "TSLA", "NASDAQ:TSLA", "Tesla Inc.", "stock", "USD", False),
    ("BRK-B", "BRK-B", "NYSE:BRK.B", "Berkshire Hathaway B", "stock", "USD", False),
    ("JPM", "JPM", "NYSE:JPM", "JPMorgan Chase & Co.", "stock", "USD", False),
    ("V", "V", "NYSE:V", "Visa Inc.", "stock", "USD", False),
    ("MA", "MA", "NYSE:MA", "Mastercard Inc.", "stock", "USD", False),
    ("UNH", "UNH", "NYSE:UNH", "UnitedHealth Group", "stock", "USD", False),
    ("HD", "HD", "NYSE:HD", "Home Depot Inc.", "stock", "USD", False),
    ("PG", "PG", "NYSE:PG", "Procter & Gamble", "stock", "USD", False),
    ("XOM", "XOM", "NYSE:XOM", "Exxon Mobil Corp.", "stock", "USD", False),
    ("CVX", "CVX", "NYSE:CVX", "Chevron Corp.", "stock", "USD", False),
    ("LLY", "LLY", "NYSE:LLY", "Eli Lilly & Co.", "stock", "USD", False),
    ("ABBV", "ABBV", "NYSE:ABBV", "AbbVie Inc.", "stock", "USD", False),
    ("MRK", "MRK", "NYSE:MRK", "Merck & Co.", "stock", "USD", False),
    ("PFE", "PFE", "NYSE:PFE", "Pfizer Inc.", "stock", "USD", False),
    ("KO", "KO", "NYSE:KO", "Coca-Cola Co.", "stock", "USD", False),
    ("PEP", "PEP", "NASDAQ:PEP", "PepsiCo Inc.", "stock", "USD", False),
    ("WMT", "WMT", "NYSE:WMT", "Walmart Inc.", "stock", "USD", False),
    ("MCD", "MCD", "NYSE:MCD", "McDonald's Corp.", "stock", "USD", False),
    ("DIS", "DIS", "NYSE:DIS", "Walt Disney Co.", "stock", "USD", False),
    ("NKE", "NKE", "NYSE:NKE", "Nike Inc.", "stock", "USD", False),
    ("CRM", "CRM", "NYSE:CRM", "Salesforce Inc.", "stock", "USD", False),
    ("ADBE", "ADBE", "NASDAQ:ADBE", "Adobe Inc.", "stock", "USD", False),
    ("ORCL", "ORCL", "NYSE:ORCL", "Oracle Corp.", "stock", "USD", False),
    ("INTC", "INTC", "NASDAQ:INTC", "Intel Corp.", "stock", "USD", False),
    ("AMD", "AMD", "NASDAQ:AMD", "Advanced Micro Devices", "stock", "USD", False),
    ("CSCO", "CSCO", "NASDAQ:CSCO", "Cisco Systems", "stock", "USD", False),
    ("QCOM", "QCOM", "NASDAQ:QCOM", "Qualcomm Inc.", "stock", "USD", False),
    ("TXN", "TXN", "NASDAQ:TXN", "Texas Instruments", "stock", "USD", False),
    ("IBM", "IBM", "NYSE:IBM", "IBM Corp.", "stock", "USD", False),
    ("BA", "BA", "NYSE:BA", "Boeing Co.", "stock", "USD", False),
    ("CAT", "CAT", "NYSE:CAT", "Caterpillar Inc.", "stock", "USD", False),
    ("GE", "GE", "NYSE:GE", "General Electric", "stock", "USD", False),
    ("MMM", "MMM", "NYSE:MMM", "3M Co.", "stock", "USD", False),
    ("HON", "HON", "NASDAQ:HON", "Honeywell International", "stock", "USD", False),
    ("GS", "GS", "NYSE:GS", "Goldman Sachs", "stock", "USD", False),
    ("MS", "MS", "NYSE:MS", "Morgan Stanley", "stock", "USD", False),
    ("BAC", "BAC", "NYSE:BAC", "Bank of America", "stock", "USD", False),
    ("WFC", "WFC", "NYSE:WFC", "Wells Fargo", "stock", "USD", False),
    ("C", "C", "NYSE:C", "Citigroup Inc.", "stock", "USD", False),
    ("AXP", "AXP", "NYSE:AXP", "American Express", "stock", "USD", False),
    ("BLK", "BLK", "NYSE:BLK", "BlackRock Inc.", "stock", "USD", False),
    ("T", "T", "NYSE:T", "AT&T Inc.", "stock", "USD", False),
    ("VZ", "VZ", "NYSE:VZ", "Verizon Communications", "stock", "USD", False),
    ("CMCSA", "CMCSA", "NASDAQ:CMCSA", "Comcast Corp.", "stock", "USD", False),
    ("NFLX", "NFLX", "NASDAQ:NFLX", "Netflix Inc.", "stock", "USD", False),
    ("PYPL", "PYPL", "NASDAQ:PYPL", "PayPal Holdings", "stock", "USD", False),
    ("SBUX", "SBUX", "NASDAQ:SBUX", "Starbucks Corp.", "stock", "USD", False),
    ("UPS", "UPS", "NYSE:UPS", "United Parcel Service", "stock", "USD", False),
    ("LOW", "LOW", "NYSE:LOW", "Lowe's Companies", "stock", "USD", False),
    ("COST", "COST", "NASDAQ:COST", "Costco Wholesale", "stock", "USD", False),
    ("TGT", "TGT", "NYSE:TGT", "Target Corp.", "stock", "USD", False),
    ("F", "F", "NYSE:F", "Ford Motor Co.", "stock", "USD", False),
    ("GM", "GM", "NYSE:GM", "General Motors", "stock", "USD", False),
    ("EBAY", "EBAY", "NASDAQ:EBAY", "eBay Inc.", "stock", "USD", False),
    ("GILD", "GILD", "NASDAQ:GILD", "Gilead Sciences", "stock", "USD", False),
    ("AMGN", "AMGN", "NASDAQ:AMGN", "Amgen Inc.", "stock", "USD", False),
    ("BMY", "BMY", "NYSE:BMY", "Bristol-Myers Squibb", "stock", "USD", False),
    ("JNJ", "JNJ", "NYSE:JNJ", "Johnson & Johnson", "stock", "USD", False),
    ("CL", "CL", "NYSE:CL", "Colgate-Palmolive", "stock", "USD", False),
    ("MO", "MO", "NYSE:MO", "Altria Group", "stock", "USD", False),
    ("DUK", "DUK", "NYSE:DUK", "Duke Energy", "stock", "USD", False),
    ("SO", "SO", "NYSE:SO", "Southern Company", "stock", "USD", False),
    ("NEE", "NEE", "NYSE:NEE", "NextEra Energy", "stock", "USD", False),
    ("LIN", "LIN", "NYSE:LIN", "Linde plc", "stock", "USD", False),
    ("DE", "DE", "NYSE:DE", "Deere & Co.", "stock", "USD", False),
    ("RTX", "RTX", "NYSE:RTX", "Raytheon Technologies", "stock", "USD", False),
    ("LMT", "LMT", "NYSE:LMT", "Lockheed Martin", "stock", "USD", False),
    ("UNP", "UNP", "NYSE:UNP", "Union Pacific", "stock", "USD", False),
    ("CVS", "CVS", "NYSE:CVS", "CVS Health", "stock", "USD", False),
    ("FDX", "FDX", "NYSE:FDX", "FedEx Corp.", "stock", "USD", False),
    ("BX", "BX", "NYSE:BX", "Blackstone Inc.", "stock", "USD", False),
    ("SCHW", "SCHW", "NYSE:SCHW", "Charles Schwab", "stock", "USD", False),
    ("INTU", "INTU", "NASDAQ:INTU", "Intuit Inc.", "stock", "USD", False),
    ("ISRG", "ISRG", "NASDAQ:ISRG", "Intuitive Surgical", "stock", "USD", False),
    ("SPGI", "SPGI", "NYSE:SPGI", "S&P Global Inc.", "stock", "USD", False),
    ("BKNG", "BKNG", "NASDAQ:BKNG", "Booking Holdings", "stock", "USD", False),
    ("VRTX", "VRTX", "NASDAQ:VRTX", "Vertex Pharmaceuticals", "stock", "USD", False),
    ("REGN", "REGN", "NASDAQ:REGN", "Regeneron Pharma", "stock", "USD", False),
    ("ZTS", "ZTS", "NYSE:ZTS", "Zoetis Inc.", "stock", "USD", False),
    ("MDLZ", "MDLZ", "NASDAQ:MDLZ", "Mondelez International", "stock", "USD", False),
    ("AMAT", "AMAT", "NASDAQ:AMAT", "Applied Materials", "stock", "USD", False),
    ("AVGO", "AVGO", "NASDAQ:AVGO", "Broadcom Inc.", "stock", "USD", False),
    ("MU", "MU", "NASDAQ:MU", "Micron Technology", "stock", "USD", False),
    ("LRCX", "LRCX", "NASDAQ:LRCX", "Lam Research", "stock", "USD", False),
    ("NOW", "NOW", "NYSE:NOW", "ServiceNow Inc.", "stock", "USD", False),
    ("PANW", "PANW", "NASDAQ:PANW", "Palo Alto Networks", "stock", "USD", False),
    ("SHOP", "SHOP", "NYSE:SHOP", "Shopify Inc.", "stock", "USD", False),
    ("UBER", "UBER", "NYSE:UBER", "Uber Technologies", "stock", "USD", False),
    ("ABNB", "ABNB", "NASDAQ:ABNB", "Airbnb Inc.", "stock", "USD", False),
    ("SQ", "SQ", "NYSE:SQ", "Block Inc.", "stock", "USD", False),
    ("COIN", "COIN", "NASDAQ:COIN", "Coinbase Global", "stock", "USD", False),
    ("DAL", "DAL", "NYSE:DAL", "Delta Air Lines", "stock", "USD", False),
    ("AAL", "AAL", "NASDAQ:AAL", "American Airlines", "stock", "USD", False),
    ("CCL", "CCL", "NYSE:CCL", "Carnival Corp.", "stock", "USD", False),
    # ---------- EU STOCKS ----------
    ("SAP", "SAP", "NYSE:SAP", "SAP SE", "stock", "EUR", False),
    ("ASML", "ASML", "NASDAQ:ASML", "ASML Holding", "stock", "EUR", False),
    ("LVMUY", "LVMUY", "OTC:LVMUY", "LVMH ADR", "stock", "USD", False),
    ("NVO", "NVO", "NYSE:NVO", "Novo Nordisk", "stock", "USD", False),
    ("SHEL", "SHEL", "NYSE:SHEL", "Shell plc", "stock", "USD", False),
    ("TM", "TM", "NYSE:TM", "Toyota Motor", "stock", "USD", False),
    ("HSBC", "HSBC", "NYSE:HSBC", "HSBC Holdings", "stock", "USD", False),
    ("BP", "BP", "NYSE:BP", "BP plc", "stock", "USD", False),
    ("BABA", "BABA", "NYSE:BABA", "Alibaba Group", "stock", "USD", False),
    ("NIO", "NIO", "NYSE:NIO", "NIO Inc.", "stock", "USD", False),
    ("PDD", "PDD", "NASDAQ:PDD", "PDD Holdings", "stock", "USD", False),
    ("JD", "JD", "NASDAQ:JD", "JD.com Inc.", "stock", "USD", False),
    # ---------- INDICES ----------
    ("SPX500", "^GSPC", "TVC:SPX", "S&P 500", "index", "USD", False),
    ("US100", "^NDX", "TVC:NDX", "Nasdaq 100", "index", "USD", False),
    ("US30", "^DJI", "TVC:DJI", "Dow Jones Industrial", "index", "USD", False),
    ("US2000", "^RUT", "TVC:RUT", "Russell 2000", "index", "USD", False),
    ("DAX40", "^GDAXI", "XETR:DAX", "DAX 40 (Germany)", "index", "EUR", False),
    ("FTSE100", "^FTSE", "TVC:UKX", "FTSE 100 (UK)", "index", "GBP", False),
    ("CAC40", "^FCHI", "TVC:CAC40", "CAC 40 (France)", "index", "EUR", False),
    ("STOXX50", "^STOXX50E", "TVC:SX5E", "Euro Stoxx 50", "index", "EUR", False),
    ("NIKKEI225", "^N225", "TVC:NI225", "Nikkei 225 (Japan)", "index", "JPY", False),
    ("HSI", "^HSI", "TVC:HSI", "Hang Seng (Hong Kong)", "index", "HKD", False),
    # ---------- COMMODITIES ----------
    ("GOLD", "GC=F", "TVC:GOLD", "Gold Futures", "commodity", "USD", False),
    ("SILVER", "SI=F", "TVC:SILVER", "Silver Futures", "commodity", "USD", False),
    ("PLATINUM", "PL=F", "TVC:PLATINUM", "Platinum Futures", "commodity", "USD", False),
    ("PALLADIUM", "PA=F", "TVC:PALLADIUM", "Palladium Futures", "commodity", "USD", False),
    ("COPPER", "HG=F", "TVC:COPPER", "Copper Futures", "commodity", "USD", False),
    ("OIL_WTI", "CL=F", "TVC:USOIL", "WTI Crude Oil", "commodity", "USD", False),
    ("OIL_BRENT", "BZ=F", "TVC:UKOIL", "Brent Crude Oil", "commodity", "USD", False),
    ("NATGAS", "NG=F", "NYMEX:NG1!", "Natural Gas", "commodity", "USD", False),
    ("CORN", "ZC=F", "CBOT:ZC1!", "Corn Futures", "commodity", "USD", False),
    ("WHEAT", "ZW=F", "CBOT:ZW1!", "Wheat Futures", "commodity", "USD", False),
    ("SOYBEAN", "ZS=F", "CBOT:ZS1!", "Soybean Futures", "commodity", "USD", False),
    ("COFFEE", "KC=F", "ICEUS:KC1!", "Coffee Futures", "commodity", "USD", False),
    ("SUGAR", "SB=F", "ICEUS:SB1!", "Sugar Futures", "commodity", "USD", False),
    ("COCOA", "CC=F", "ICEUS:CC1!", "Cocoa Futures", "commodity", "USD", False),
    # ---------- FX (USD CROSSES, ALL 'X=F' SUFFIXES) ----------
    ("EURUSD", "EURUSD=X", "FX:EURUSD", "Euro vs US Dollar", "fx", "USD", False),
    ("GBPUSD", "GBPUSD=X", "FX:GBPUSD", "Pound vs US Dollar", "fx", "USD", False),
    ("USDJPY", "USDJPY=X", "FX:USDJPY", "Dollar vs Yen", "fx", "JPY", False),
    ("USDCHF", "USDCHF=X", "FX:USDCHF", "Dollar vs Swiss Franc", "fx", "CHF", False),
    ("AUDUSD", "AUDUSD=X", "FX:AUDUSD", "Aussie vs US Dollar", "fx", "USD", False),
    ("NZDUSD", "NZDUSD=X", "FX:NZDUSD", "Kiwi vs US Dollar", "fx", "USD", False),
    ("USDCAD", "USDCAD=X", "FX:USDCAD", "Dollar vs Canadian", "fx", "CAD", False),
    ("EURGBP", "EURGBP=X", "FX:EURGBP", "Euro vs Pound", "fx", "GBP", False),
    ("EURJPY", "EURJPY=X", "FX:EURJPY", "Euro vs Yen", "fx", "JPY", False),
    ("GBPJPY", "GBPJPY=X", "FX:GBPJPY", "Pound vs Yen", "fx", "JPY", False),
    ("AUDJPY", "AUDJPY=X", "FX:AUDJPY", "Aussie vs Yen", "fx", "JPY", False),
    ("AUDCAD", "AUDCAD=X", "FX:AUDCAD", "Aussie vs Canadian", "fx", "CAD", False),
    ("AUDNZD", "AUDNZD=X", "FX:AUDNZD", "Aussie vs Kiwi", "fx", "NZD", False),
    ("EURCHF", "EURCHF=X", "FX:EURCHF", "Euro vs Swiss Franc", "fx", "CHF", False),
    # ---------- CRYPTO (weekly resolution recommended) ----------
    ("BTCUSD", "BTC-USD", "BINANCE:BTCUSDT", "Bitcoin", "crypto", "USD", True),
    ("ETHUSD", "ETH-USD", "BINANCE:ETHUSDT", "Ethereum", "crypto", "USD", True),
    ("BNBUSD", "BNB-USD", "BINANCE:BNBUSDT", "BNB", "crypto", "USD", True),
    ("XRPUSD", "XRP-USD", "BINANCE:XRPUSDT", "Ripple", "crypto", "USD", True),
    ("ADAUSD", "ADA-USD", "BINANCE:ADAUSDT", "Cardano", "crypto", "USD", True),
    ("SOLUSD", "SOL-USD", "BINANCE:SOLUSDT", "Solana", "crypto", "USD", True),
    ("DOTUSD", "DOT-USD", "BINANCE:DOTUSDT", "Polkadot", "crypto", "USD", True),
    ("DOGEUSD", "DOGE-USD", "BINANCE:DOGEUSDT", "Dogecoin", "crypto", "USD", True),
    ("LTCUSD", "LTC-USD", "BINANCE:LTCUSDT", "Litecoin", "crypto", "USD", True),
    ("AVAXUSD", "AVAX-USD", "BINANCE:AVAXUSDT", "Avalanche", "crypto", "USD", True),
    ("LINKUSD", "LINK-USD", "BINANCE:LINKUSDT", "Chainlink", "crypto", "USD", True),
    ("MATICUSD", "MATIC-USD", "BINANCE:MATICUSDT", "Polygon", "crypto", "USD", True),
    ("UNIUSD", "UNI7083-USD", "BINANCE:UNIUSDT", "Uniswap", "crypto", "USD", True),
    ("BCHUSD", "BCH-USD", "BINANCE:BCHUSDT", "Bitcoin Cash", "crypto", "USD", True),
    ("XLMUSD", "XLM-USD", "BINANCE:XLMUSDT", "Stellar", "crypto", "USD", True),
    ("ATOMUSD", "ATOM-USD", "BINANCE:ATOMUSDT", "Cosmos", "crypto", "USD", True),
    ("ETCUSD", "ETC-USD", "BINANCE:ETCUSDT", "Ethereum Classic", "crypto", "USD", True),
    # ---------- ETFs (broad market exposures) ----------
    ("SPY", "SPY", "AMEX:SPY", "SPDR S&P 500 ETF", "etf", "USD", False),
    ("QQQ", "QQQ", "NASDAQ:QQQ", "Invesco QQQ Trust", "etf", "USD", False),
    ("DIA", "DIA", "AMEX:DIA", "SPDR Dow Jones ETF", "etf", "USD", False),
    ("IWM", "IWM", "AMEX:IWM", "iShares Russell 2000", "etf", "USD", False),
    ("EFA", "EFA", "AMEX:EFA", "iShares MSCI EAFE", "etf", "USD", False),
    ("EEM", "EEM", "AMEX:EEM", "iShares MSCI Emerging Mkts", "etf", "USD", False),
    ("GLD", "GLD", "AMEX:GLD", "SPDR Gold Shares", "etf", "USD", False),
    ("SLV", "SLV", "AMEX:SLV", "iShares Silver Trust", "etf", "USD", False),
    ("USO", "USO", "AMEX:USO", "United States Oil Fund", "etf", "USD", False),
    ("TLT", "TLT", "NASDAQ:TLT", "iShares 20Y Treasury", "etf", "USD", False),
    ("HYG", "HYG", "AMEX:HYG", "iShares High Yield", "etf", "USD", False),
    ("XLE", "XLE", "AMEX:XLE", "Energy Select Sector", "etf", "USD", False),
    ("XLF", "XLF", "AMEX:XLF", "Financial Select Sector", "etf", "USD", False),
    ("XLK", "XLK", "AMEX:XLK", "Technology Select Sector", "etf", "USD", False),
    ("XLV", "XLV", "AMEX:XLV", "Health Care Select", "etf", "USD", False),
    ("XLY", "XLY", "AMEX:XLY", "Consumer Discretionary", "etf", "USD", False),
    ("XLP", "XLP", "AMEX:XLP", "Consumer Staples", "etf", "USD", False),
    ("VWO", "VWO", "AMEX:VWO", "Vanguard Emerging Mkts", "etf", "USD", False),
    ("VEA", "VEA", "AMEX:VEA", "Vanguard FTSE Developed", "etf", "USD", False),
    ("VNQ", "VNQ", "AMEX:VNQ", "Vanguard Real Estate", "etf", "USD", False),
    ("ARKK", "ARKK", "AMEX:ARKK", "ARK Innovation ETF", "etf", "USD", False),
    ("ARKG", "ARKG", "AMEX:ARKG", "ARK Genomics ETF", "etf", "USD", False),
    ("ARKW", "ARKW", "AMEX:ARKW", "ARK Web ETF", "etf", "USD", False),
    ("SMH", "SMH", "NASDAQ:SMH", "VanEck Semiconductors", "etf", "USD", False),
    ("XBI", "XBI", "AMEX:XBI", "SPDR S&P Biotech", "etf", "USD", False),
]
