"""Curated seed of Libertex MT5-Market CFDs.
Auto-generated from data/libertex_raw.json (scraped from
https://libertex.org/cfd-specification — MT5-Market platform).

Each row: (symbol, yf_symbol, tv_symbol, name, category, currency, is_crypto)
"""

LIBERTEX_SEED = [
    # ---------- STOCK (1245) ----------
    ("AA", "AA", None, "AA", "stock", "USD", False),
    ("AAL", "AAL", None, "AAL", "stock", "USD", False),
    ("AAPL", "AAPL", None, "AAPL", "stock", "USD", False),
    ("ABBV", "ABBV", None, "ABBV", "stock", "USD", False),
    ("ABCL", "ABCL", None, "ABCL", "stock", "USD", False),
    ("ABNB", "ABNB", None, "ABNB", "stock", "USD", False),
    ("ABT", "ABT", None, "ABT", "stock", "USD", False),
    ("ACAD", "ACAD", None, "ACAD", "stock", "USD", False),
    ("ACB", "ACB", None, "ACB", "stock", "USD", False),
    ("ACGL", "ACGL", None, "ACGL", "stock", "USD", False),
    ("ACIW", "ACIW", None, "ACIW", "stock", "USD", False),
    ("ACM", "ACM", None, "ACM", "stock", "USD", False),
    ("ACN", "ACN", None, "ACN", "stock", "USD", False),
    ("ADBE", "ADBE", None, "ADBE", "stock", "USD", False),
    ("ADI", "ADI", None, "ADI", "stock", "USD", False),
    ("ADM", "ADM", None, "ADM", "stock", "USD", False),
    ("ADNT", "ADNT", None, "ADNT", "stock", "USD", False),
    ("ADP", "ADP", None, "ADP", "stock", "USD", False),
    ("ADPT", "ADPT", None, "ADPT", "stock", "USD", False),
    ("ADS", "ADS", None, "ADS", "stock", "USD", False),
    ("ADSK", "ADSK", None, "ADSK", "stock", "USD", False),
    ("AEE", "AEE", None, "AEE", "stock", "USD", False),
    ("AEIS", "AEIS", None, "AEIS", "stock", "USD", False),
    ("AEM", "AEM", None, "AEM", "stock", "USD", False),
    ("AEP", "AEP", None, "AEP", "stock", "USD", False),
    ("AER", "AER", None, "AER", "stock", "USD", False),
    ("AES", "AES", None, "AES", "stock", "USD", False),
    ("AF", "AF.PA", None, "Air France-KLM", "stock", "EUR", False),
    ("AFG", "AFG", None, "AFG", "stock", "USD", False),
    ("AFL", "AFL", None, "AFL", "stock", "USD", False),
    ("AFRM", "AFRM", None, "AFRM", "stock", "USD", False),
    ("AG", "AG", None, "AG", "stock", "USD", False),
    ("AGCO", "AGCO", None, "AGCO", "stock", "USD", False),
    ("AGI", "AGI", None, "AGI", "stock", "USD", False),
    ("AGNC", "AGNC", None, "AGNC", "stock", "USD", False),
    ("AGNCM", "AGNCM", None, "AGNCM", "stock", "USD", False),
    ("AI", "AI", None, "AI", "stock", "USD", False),
    ("AIG", "AIG", None, "AIG", "stock", "USD", False),
    ("AIR", "AIR.PA", None, "Airbus SE", "stock", "EUR", False),
    ("AIZ", "AIZ", None, "AIZ", "stock", "USD", False),
    ("AJG", "AJG", None, "AJG", "stock", "USD", False),
    ("AKAM", "AKAM", None, "AKAM", "stock", "USD", False),
    ("ALAB", "ALAB", None, "ALAB", "stock", "USD", False),
    ("ALB", "ALB", None, "ALB", "stock", "USD", False),
    ("ALC", "ALC", None, "ALC", "stock", "USD", False),
    ("ALGN", "ALGN", None, "ALGN", "stock", "USD", False),
    ("ALK", "ALK", None, "ALK", "stock", "USD", False),
    ("ALKS", "ALKS", None, "ALKS", "stock", "USD", False),
    ("ALL", "ALL", None, "ALL", "stock", "USD", False),
    ("ALLE", "ALLE", None, "ALLE", "stock", "USD", False),
    ("ALLY", "ALLY", None, "ALLY", "stock", "USD", False),
    ("ALNY", "ALNY", None, "ALNY", "stock", "USD", False),
    ("ALSN", "ALSN", None, "ALSN", "stock", "USD", False),
    ("AMAT", "AMAT", None, "AMAT", "stock", "USD", False),
    ("AMBA", "AMBA", None, "AMBA", "stock", "USD", False),
    ("AMC", "AMC", None, "AMC Entertainment", "stock", "USD", False),
    ("AMD", "AMD", None, "AMD", "stock", "USD", False),
    ("AME", "AME", None, "AME", "stock", "USD", False),
    ("AMGN", "AMGN", None, "AMGN", "stock", "USD", False),
    ("AMH", "AMH", None, "AMH", "stock", "USD", False),
    ("AMP", "AMP", None, "AMP", "stock", "USD", False),
    ("AMT", "AMT", None, "AMT", "stock", "USD", False),
    ("AMX", "AMX", None, "America Movil", "stock", "USD", False),
    ("AMZN", "AMZN", None, "AMZN", "stock", "USD", False),
    ("AN", "AN", None, "AN", "stock", "USD", False),
    ("ANET", "ANET", None, "ANET", "stock", "USD", False),
    ("AON", "AON", None, "AON", "stock", "USD", False),
    ("AOS", "AOS", None, "AOS", "stock", "USD", False),
    ("APA", "APA", None, "APA", "stock", "USD", False),
    ("APD", "APD", None, "APD", "stock", "USD", False),
    ("APG", "APG", None, "APG", "stock", "USD", False),
    ("APH", "APH", None, "APH", "stock", "USD", False),
    ("APLS", "APLS", None, "APLS", "stock", "USD", False),
    ("APO", "APO", None, "APO", "stock", "USD", False),
    ("APP", "APP", None, "APP", "stock", "USD", False),
    ("APPN", "APPN", None, "APPN", "stock", "USD", False),
    ("APTV", "APTV", None, "APTV", "stock", "USD", False),
    ("ARCC", "ARCC", None, "ARCC", "stock", "USD", False),
    ("ARE", "ARE", None, "ARE", "stock", "USD", False),
    ("ARES", "ARES", None, "ARES", "stock", "USD", False),
    ("ARGX", "ARGX", None, "ARGX", "stock", "USD", False),
    ("ARM", "ARM", None, "ARM", "stock", "USD", False),
    ("ARMK", "ARMK", None, "ARMK", "stock", "USD", False),
    ("ARRY", "ARRY", None, "ARRY", "stock", "USD", False),
    ("ARW", "ARW", None, "ARW", "stock", "USD", False),
    ("ARWR", "ARWR", None, "ARWR", "stock", "USD", False),
    ("AS", "AS", None, "AS", "stock", "USD", False),
    ("ASAN", "ASAN", None, "ASAN", "stock", "USD", False),
    ("ASH", "ASH", None, "ASH", "stock", "USD", False),
    ("ASML", "ASML", None, "ASML", "stock", "USD", False),
    ("ASND", "ASND", None, "ASND", "stock", "USD", False),
    ("ASTS", "ASTS", None, "ASTS", "stock", "USD", False),
    ("ASX", "ASX", None, "ASX", "stock", "USD", False),
    ("ATI", "ATI", None, "ATI", "stock", "USD", False),
    ("ATO", "ATO", None, "ATO", "stock", "USD", False),
    ("ATR", "ATR", None, "ATR", "stock", "USD", False),
    ("AU", "AU", None, "AU", "stock", "USD", False),
    ("AVAV", "AVAV", None, "AVAV", "stock", "USD", False),
    ("AVB", "AVB", None, "AVB", "stock", "USD", False),
    ("AVGO", "AVGO", None, "AVGO", "stock", "USD", False),
    ("AVNT", "AVNT", None, "AVNT", "stock", "USD", False),
    ("AVT", "AVT", None, "AVT", "stock", "USD", False),
    ("AVTR", "AVTR", None, "AVTR", "stock", "USD", False),
    ("AVY", "AVY", None, "AVY", "stock", "USD", False),
    ("AWK", "AWK", None, "AWK", "stock", "USD", False),
    ("AXON", "AXON", None, "AXON", "stock", "USD", False),
    ("AXP", "AXP", None, "AXP", "stock", "USD", False),
    ("AXS", "AXS", None, "AXS", "stock", "USD", False),
    ("AYI", "AYI", None, "AYI", "stock", "USD", False),
    ("AZN", "AZN", None, "AZN", "stock", "USD", False),
    ("AZO", "AZO", None, "AZO", "stock", "USD", False),
    ("BA", "BA", None, "BA", "stock", "USD", False),
    ("BABA", "BABA", None, "BABA", "stock", "USD", False),
    ("BAC", "BAC", None, "BAC", "stock", "USD", False),
    ("BAH", "BAH", None, "BAH", "stock", "USD", False),
    ("BALL", "BALL", None, "BALL", "stock", "USD", False),
    ("BAM", "BAM", None, "BAM", "stock", "USD", False),
    ("BAP", "BAP", None, "BAP", "stock", "USD", False),
    ("BAS", "BAS.DE", None, "BASF SE", "stock", "EUR", False),
    ("BAX", "BAX", None, "BAX", "stock", "USD", False),
    ("BAYN", "BAYN", None, "BAYN", "stock", "USD", False),
    ("BB", "BB", None, "BB", "stock", "USD", False),
    ("BBIO", "BBIO", None, "BBIO", "stock", "USD", False),
    ("BBVA", "BBVA", None, "BBVA", "stock", "USD", False),
    ("BBWI", "BBWI", None, "BBWI", "stock", "USD", False),
    ("BBY", "BBY", None, "BBY", "stock", "USD", False),
    ("BC", "BC", None, "BC", "stock", "USD", False),
    ("BCE", "BCE", None, "BCE", "stock", "USD", False),
    ("BCH", "BCH", None, "BCH", "stock", "USD", False),
    ("BCS", "BCS", None, "BCS", "stock", "USD", False),
    ("BDX", "BDX", None, "BDX", "stock", "USD", False),
    ("BE", "BE", None, "BE", "stock", "USD", False),
    ("BEKE", "BEKE", None, "BEKE", "stock", "USD", False),
    ("BEN", "BEN", None, "BEN", "stock", "USD", False),
    ("BEP", "BEP", None, "BEP", "stock", "USD", False),
    ("BEPC", "BEPC", None, "BEPC", "stock", "USD", False),
    ("BFAM", "BFAM", None, "BFAM", "stock", "USD", False),
    ("BG", "BG", None, "BG", "stock", "USD", False),
    ("BHC", "BHC", None, "BHC", "stock", "USD", False),
    ("BHP", "BHP", None, "BHP", "stock", "USD", False),
    ("BIDU", "BIDU", None, "BIDU", "stock", "USD", False),
    ("BIIB", "BIIB", None, "BIIB", "stock", "USD", False),
    ("BILI", "BILI", None, "BILI", "stock", "USD", False),
    ("BIO", "BIO", None, "BIO", "stock", "USD", False),
    ("BIP", "BIP", None, "BIP", "stock", "USD", False),
    ("BIRK", "BIRK", None, "BIRK", "stock", "USD", False),
    ("BJ", "BJ", None, "BJ", "stock", "USD", False),
    ("BK", "BK", None, "BK", "stock", "USD", False),
    ("BKNG", "BKNG", None, "BKNG", "stock", "USD", False),
    ("BKR", "BKR", None, "BKR", "stock", "USD", False),
    ("BLD", "BLD", None, "BLD", "stock", "USD", False),
    ("BLDR", "BLDR", None, "BLDR", "stock", "USD", False),
    ("BLK", "BLK", None, "BLK", "stock", "USD", False),
    ("BLKB", "BLKB", None, "BLKB", "stock", "USD", False),
    ("BLSH", "BLSH", None, "BLSH", "stock", "USD", False),
    ("BMBL", "BMBL", None, "BMBL", "stock", "USD", False),
    ("BMNR", "BMNR", None, "BMNR", "stock", "USD", False),
    ("BMO", "BMO", None, "BMO", "stock", "USD", False),
    ("BMRN", "BMRN", None, "BMRN", "stock", "USD", False),
    ("BMW", "BMW.DE", None, "BMW AG", "stock", "EUR", False),
    ("BMY", "BMY", None, "BMY", "stock", "USD", False),
    ("BN", "BN", None, "BN", "stock", "USD", False),
    ("BNGO", "BNGO", None, "BNGO", "stock", "USD", False),
    ("BNP", "BNP.PA", None, "BNP Paribas", "stock", "EUR", False),
    ("BNS", "BNS", None, "BNS", "stock", "USD", False),
    ("BNT", "BNT", None, "BNT", "stock", "USD", False),
    ("BNTX", "BNTX", None, "BNTX", "stock", "USD", False),
    ("BOKF", "BOKF", None, "BOKF", "stock", "USD", False),
    ("BPOP", "BPOP", None, "BPOP", "stock", "USD", False),
    ("BR", "BR", None, "BR", "stock", "USD", False),
    ("BRKR", "BRKR", None, "BRKR", "stock", "USD", False),
    ("BRO", "BRO", None, "BRO", "stock", "USD", False),
    ("BRSL", "BRSL", None, "BRSL", "stock", "USD", False),
    ("BSAC", "BSAC", None, "BSAC", "stock", "USD", False),
    ("BSX", "BSX", None, "BSX", "stock", "USD", False),
    ("BSY", "BSY", None, "BSY", "stock", "USD", False),
    ("BTI", "BTI", None, "BTI", "stock", "USD", False),
    ("BUD", "BUD", None, "BUD", "stock", "USD", False),
    ("BURL", "BURL", None, "BURL", "stock", "USD", False),
    ("BWA", "BWA", None, "BWA", "stock", "USD", False),
    ("BWXT", "BWXT", None, "BWXT", "stock", "USD", False),
    ("BX", "BX", None, "BX", "stock", "USD", False),
    ("BXP", "BXP", None, "BXP", "stock", "USD", False),
    ("CACI", "CACI", None, "CACI", "stock", "USD", False),
    ("CAG", "CAG", None, "CAG", "stock", "USD", False),
    ("CAH", "CAH", None, "CAH", "stock", "USD", False),
    ("CARR", "CARR", None, "CARR", "stock", "USD", False),
    ("CASY", "CASY", None, "CASY", "stock", "USD", False),
    ("CAT", "CAT", None, "CAT", "stock", "USD", False),
    ("CB", "CB", None, "CB", "stock", "USD", False),
    ("CBRE", "CBRE", None, "CBRE", "stock", "USD", False),
    ("CBSH", "CBSH", None, "CBSH", "stock", "USD", False),
    ("CCEP", "CCEP", None, "CCEP", "stock", "USD", False),
    ("CCI", "CCI", None, "CCI", "stock", "USD", False),
    ("CCJ", "CCJ", None, "CCJ", "stock", "USD", False),
    ("CCK", "CCK", None, "CCK", "stock", "USD", False),
    ("CCL", "CCL", None, "Carnival Corp.", "stock", "USD", False),
    ("CDNS", "CDNS", None, "CDNS", "stock", "USD", False),
    ("CDW", "CDW", None, "CDW", "stock", "USD", False),
    ("CE", "CE", None, "CE", "stock", "USD", False),
    ("CEG", "CEG", None, "CEG", "stock", "USD", False),
    ("CELH", "CELH", None, "CELH", "stock", "USD", False),
    ("CERS", "CERS", None, "CERS", "stock", "USD", False),
    ("CERT", "CERT", None, "CERT", "stock", "USD", False),
    ("CF", "CF", None, "CF", "stock", "USD", False),
    ("CFG", "CFG", None, "CFG", "stock", "USD", False),
    ("CFR", "CFR", None, "CFR", "stock", "USD", False),
    ("CG", "CG", None, "CG", "stock", "USD", False),
    ("CGC", "CGC", None, "CGC", "stock", "USD", False),
    ("CGNX", "CGNX", None, "CGNX", "stock", "USD", False),
    ("CHD", "CHD", None, "CHD", "stock", "USD", False),
    ("CHKP", "CHKP", None, "CHKP", "stock", "USD", False),
    ("CHRW", "CHRW", None, "CHRW", "stock", "USD", False),
    ("CHT", "CHT", None, "CHT", "stock", "USD", False),
    ("CHTR", "CHTR", None, "CHTR", "stock", "USD", False),
    ("CHWY", "CHWY", None, "CHWY", "stock", "USD", False),
    ("CHYM", "CHYM", None, "CHYM", "stock", "USD", False),
    ("CI", "CI", None, "CI", "stock", "USD", False),
    ("CIB", "CIB", None, "Bancolombia", "stock", "USD", False),
    ("CIEN", "CIEN", None, "CIEN", "stock", "USD", False),
    ("CINF", "CINF", None, "CINF", "stock", "USD", False),
    ("CLF", "CLF", None, "CLF", "stock", "USD", False),
    ("CLH", "CLH", None, "CLH", "stock", "USD", False),
    ("CLS", "CLS", None, "CLS", "stock", "USD", False),
    ("CLSK", "CLSK", None, "CLSK", "stock", "USD", False),
    ("CLX", "CLX", None, "CLX", "stock", "USD", False),
    ("CM", "CM", None, "CM", "stock", "USD", False),
    ("CMCSA", "CMCSA", None, "CMCSA", "stock", "USD", False),
    ("CME", "CME", None, "CME", "stock", "USD", False),
    ("CMG", "CMG", None, "CMG", "stock", "USD", False),
    ("CMI", "CMI", None, "CMI", "stock", "USD", False),
    ("CMS", "CMS", None, "CMS", "stock", "USD", False),
    ("CNA", "CNA", None, "CNA", "stock", "USD", False),
    ("CNC", "CNC", None, "CNC", "stock", "USD", False),
    ("CNI", "CNI", None, "CNI", "stock", "USD", False),
    ("CNP", "CNP", None, "CNP", "stock", "USD", False),
    ("CNQ", "CNQ", None, "CNQ", "stock", "USD", False),
    ("COF", "COF", None, "COF", "stock", "USD", False),
    ("COHR", "COHR", None, "COHR", "stock", "USD", False),
    ("COIN", "COIN", None, "Coinbase Global", "stock", "USD", False),
    ("COLM", "COLM", None, "COLM", "stock", "USD", False),
    ("COO", "COO", None, "COO", "stock", "USD", False),
    ("COP", "COP", None, "COP", "stock", "USD", False),
    ("COR", "COR", None, "COR", "stock", "USD", False),
    ("COST", "COST", None, "COST", "stock", "USD", False),
    ("CP", "CP", None, "CP", "stock", "USD", False),
    ("CPA", "CPA", None, "CPA", "stock", "USD", False),
    ("CPAY", "CPAY", None, "CPAY", "stock", "USD", False),
    ("CPB", "CPB", None, "CPB", "stock", "USD", False),
    ("CPNG", "CPNG", None, "CPNG", "stock", "USD", False),
    ("CPRI", "CPRI", None, "CPRI", "stock", "USD", False),
    ("CPRT", "CPRT", None, "CPRT", "stock", "USD", False),
    ("CPT", "CPT", None, "CPT", "stock", "USD", False),
    ("CQP", "CQP", None, "CQP", "stock", "USD", False),
    ("CR", "CR", None, "CR", "stock", "USD", False),
    ("CRBG", "CRBG", None, "CRBG", "stock", "USD", False),
    ("CRCL", "CRCL", None, "CRCL", "stock", "USD", False),
    ("CRDO", "CRDO", None, "CRDO", "stock", "USD", False),
    ("CRH", "CRH", None, "CRH", "stock", "USD", False),
    ("CRI", "CRI", None, "CRI", "stock", "USD", False),
    ("CRM", "CRM", None, "CRM", "stock", "USD", False),
    ("CRON", "CRON", None, "CRON", "stock", "USD", False),
    ("CRS", "CRS", None, "CRS", "stock", "USD", False),
    ("CRSR", "CRSR", None, "CRSR", "stock", "USD", False),
    ("CRUS", "CRUS", None, "CRUS", "stock", "USD", False),
    ("CRWD", "CRWD", None, "CRWD", "stock", "USD", False),
    ("CRWV", "CRWV", None, "CRWV", "stock", "USD", False),
    ("CSCO", "CSCO", None, "CSCO", "stock", "USD", False),
    ("CSGP", "CSGP", None, "CSGP", "stock", "USD", False),
    ("CSIQ", "CSIQ", None, "CSIQ", "stock", "USD", False),
    ("CSL", "CSL", None, "CSL", "stock", "USD", False),
    ("CSX", "CSX", None, "CSX", "stock", "USD", False),
    ("CTAS", "CTAS", None, "CTAS", "stock", "USD", False),
    ("CTSH", "CTSH", None, "CTSH", "stock", "USD", False),
    ("CTVA", "CTVA", None, "CTVA", "stock", "USD", False),
    ("CVE", "CVE", None, "CVE", "stock", "USD", False),
    ("CVNA", "CVNA", None, "CVNA", "stock", "USD", False),
    ("CVS", "CVS", None, "CVS", "stock", "USD", False),
    ("CW", "CW", None, "CW", "stock", "USD", False),
    ("CWBC", "CWBC", None, "CWBC", "stock", "USD", False),
    ("CX", "CX", None, "Cemex SAB", "stock", "USD", False),
    ("CXM", "CXM", None, "CXM", "stock", "USD", False),
    ("CYBR", "CYBR", None, "CYBR", "stock", "USD", False),
    ("CZR", "CZR", None, "CZR", "stock", "USD", False),
    ("DAL", "DAL", None, "DAL", "stock", "USD", False),
    ("DBK", "DBK", None, "DBK", "stock", "USD", False),
    ("DBX", "DBX", None, "DBX", "stock", "USD", False),
    ("DCI", "DCI", None, "DCI", "stock", "USD", False),
    ("DDOG", "DDOG", None, "DDOG", "stock", "USD", False),
    ("DE", "DE", None, "DE", "stock", "USD", False),
    ("DECK", "DECK", None, "DECK", "stock", "USD", False),
    ("DEI", "DEI", None, "DEI", "stock", "USD", False),
    ("DELL", "DELL", None, "DELL", "stock", "USD", False),
    ("DEO", "DEO", None, "DEO", "stock", "USD", False),
    ("DG", "DG", None, "Dollar General", "stock", "USD", False),
    ("DGX", "DGX", None, "DGX", "stock", "USD", False),
    ("DHI", "DHI", None, "DHI", "stock", "USD", False),
    ("DHR", "DHR", None, "DHR", "stock", "USD", False),
    ("DIS", "DIS", None, "DIS", "stock", "USD", False),
    ("DJT", "DJT", None, "DJT", "stock", "USD", False),
    ("DKNG", "DKNG", None, "DKNG", "stock", "USD", False),
    ("DKS", "DKS", None, "DKS", "stock", "USD", False),
    ("DLB", "DLB", None, "DLB", "stock", "USD", False),
    ("DLR", "DLR", None, "DLR", "stock", "USD", False),
    ("DLTR", "DLTR", None, "DLTR", "stock", "USD", False),
    ("DNLI", "DNLI", None, "DNLI", "stock", "USD", False),
    ("DOC", "DOC", None, "DOC", "stock", "USD", False),
    ("DOCS", "DOCS", None, "DOCS", "stock", "USD", False),
    ("DOCU", "DOCU", None, "DOCU", "stock", "USD", False),
    ("DOV", "DOV", None, "DOV", "stock", "USD", False),
    ("DOW", "DOW", None, "DOW", "stock", "USD", False),
    ("DOX", "DOX", None, "DOX", "stock", "USD", False),
    ("DPZ", "DPZ", None, "DPZ", "stock", "USD", False),
    ("DRI", "DRI", None, "DRI", "stock", "USD", False),
    ("DT", "DT", None, "DT", "stock", "USD", False),
    ("DTE", "DTE", None, "DTE", "stock", "USD", False),
    ("DTM", "DTM", None, "DTM", "stock", "USD", False),
    ("DUK", "DUK", None, "DUK", "stock", "USD", False),
    ("DUOL", "DUOL", None, "DUOL", "stock", "USD", False),
    ("DVA", "DVA", None, "DVA", "stock", "USD", False),
    ("DVN", "DVN", None, "DVN", "stock", "USD", False),
    ("DXCM", "DXCM", None, "DXCM", "stock", "USD", False),
    ("EA", "EA", None, "EA", "stock", "USD", False),
    ("EBAY", "EBAY", None, "EBAY", "stock", "USD", False),
    ("EC", "EC", None, "Ecopetrol SA", "stock", "USD", False),
    ("ECL", "ECL", None, "ECL", "stock", "USD", False),
    ("ED", "ED", None, "ED", "stock", "USD", False),
    ("EDU", "EDU", None, "EDU", "stock", "USD", False),
    ("EFX", "EFX", None, "EFX", "stock", "USD", False),
    ("EG", "EG", None, "EG", "stock", "USD", False),
    ("EGP", "EGP", None, "EGP", "stock", "USD", False),
    ("EHC", "EHC", None, "EHC", "stock", "USD", False),
    ("EIX", "EIX", None, "EIX", "stock", "USD", False),
    ("EL", "EL", None, "EL", "stock", "USD", False),
    ("ELAN", "ELAN", None, "ELAN", "stock", "USD", False),
    ("ELS", "ELS", None, "ELS", "stock", "USD", False),
    ("ELV", "ELV", None, "ELV", "stock", "USD", False),
    ("EMA", "EMA", None, "EMA", "stock", "USD", False),
    ("EMBJ", "EMBJ", None, "EMBJ", "stock", "USD", False),
    ("EME", "EME", None, "EME", "stock", "USD", False),
    ("EMN", "EMN", None, "EMN", "stock", "USD", False),
    ("EMR", "EMR", None, "EMR", "stock", "USD", False),
    ("ENB", "ENB", None, "ENB", "stock", "USD", False),
    ("ENEL", "ENEL.MI", None, "Enel SpA", "stock", "EUR", False),
    ("ENI", "ENI.MI", None, "Eni SpA", "stock", "EUR", False),
    ("ENIC", "ENIC", None, "Entel Chile", "stock", "USD", False),
    ("ENOV", "ENOV", None, "ENOV", "stock", "USD", False),
    ("ENR", "ENR", None, "ENR", "stock", "USD", False),
    ("ENS", "ENS", None, "ENS", "stock", "USD", False),
    ("ENTG", "ENTG", None, "ENTG", "stock", "USD", False),
    ("EOG", "EOG", None, "EOG", "stock", "USD", False),
    ("EPD", "EPD", None, "EPD", "stock", "USD", False),
    ("EQH", "EQH", None, "EQH", "stock", "USD", False),
    ("EQIX", "EQIX", None, "EQIX", "stock", "USD", False),
    ("EQNR", "EQNR", None, "EQNR", "stock", "USD", False),
    ("EQR", "EQR", None, "EQR", "stock", "USD", False),
    ("EQT", "EQT", None, "EQT", "stock", "USD", False),
    ("ERIE", "ERIE", None, "ERIE", "stock", "USD", False),
    ("ESLT", "ESLT", None, "ESLT", "stock", "USD", False),
    ("ESS", "ESS", None, "ESS", "stock", "USD", False),
    ("ET", "ET", None, "ET", "stock", "USD", False),
    ("ETH", "ETH", None, "ETH", "stock", "USD", False),
    ("ETN", "ETN", None, "ETN", "stock", "USD", False),
    ("ETR", "ETR", None, "ETR", "stock", "USD", False),
    ("ETSY", "ETSY", None, "ETSY", "stock", "USD", False),
    ("EVR", "EVR", None, "EVR", "stock", "USD", False),
    ("EVRG", "EVRG", None, "EVRG", "stock", "USD", False),
    ("EW", "EW", None, "EW", "stock", "USD", False),
    ("EWBC", "EWBC", None, "EWBC", "stock", "USD", False),
    ("EXAS", "EXAS", None, "EXAS", "stock", "USD", False),
    ("EXC", "EXC", None, "EXC", "stock", "USD", False),
    ("EXE", "EXE", None, "EXE", "stock", "USD", False),
    ("EXEL", "EXEL", None, "EXEL", "stock", "USD", False),
    ("EXP", "EXP", None, "EXP", "stock", "USD", False),
    ("EXPD", "EXPD", None, "EXPD", "stock", "USD", False),
    ("EXPE", "EXPE", None, "EXPE", "stock", "USD", False),
    ("EXR", "EXR", None, "EXR", "stock", "USD", False),
    ("FA", "FA", None, "FA", "stock", "USD", False),
    ("FANG", "FANG", None, "FANG", "stock", "USD", False),
    ("FAST", "FAST", None, "FAST", "stock", "USD", False),
    ("FBIN", "FBIN", None, "FBIN", "stock", "USD", False),
    ("FCNCA", "FCNCA", None, "FCNCA", "stock", "USD", False),
    ("FCX", "FCX", None, "FCX", "stock", "USD", False),
    ("FDS", "FDS", None, "FDS", "stock", "USD", False),
    ("FDX", "FDX", None, "FDX", "stock", "USD", False),
    ("FE", "FE", None, "FE", "stock", "USD", False),
    ("FER", "FER", None, "FER", "stock", "USD", False),
    ("FERG", "FERG", None, "FERG", "stock", "USD", False),
    ("FFIV", "FFIV", None, "FFIV", "stock", "USD", False),
    ("FHN", "FHN", None, "FHN", "stock", "USD", False),
    ("FICO", "FICO", None, "FICO", "stock", "USD", False),
    ("FIG", "FIG", None, "FIG", "stock", "USD", False),
    ("FIGS", "FIGS", None, "FIGS", "stock", "USD", False),
    ("FIS", "FIS", None, "FIS", "stock", "USD", False),
    ("FISV", "FISV", None, "FISV", "stock", "USD", False),
    ("FITB", "FITB", None, "FITB", "stock", "USD", False),
    ("FIX", "FIX", None, "FIX", "stock", "USD", False),
    ("FIZZ", "FIZZ", None, "FIZZ", "stock", "USD", False),
    ("FLEX", "FLEX", None, "FLEX", "stock", "USD", False),
    ("FLG", "FLG", None, "FLG", "stock", "USD", False),
    ("FLO", "FLO", None, "FLO", "stock", "USD", False),
    ("FLS", "FLS", None, "FLS", "stock", "USD", False),
    ("FLUT", "FLUT", None, "FLUT", "stock", "USD", False),
    ("FLYW", "FLYW", None, "FLYW", "stock", "USD", False),
    ("FMC", "FMC", None, "FMC", "stock", "USD", False),
    ("FMS", "FMS", None, "FMS", "stock", "USD", False),
    ("FMX", "FMX", None, "FMX", "stock", "USD", False),
    ("FN", "FN", None, "FN", "stock", "USD", False),
    ("FNF", "FNF", None, "FNF", "stock", "USD", False),
    ("FNV", "FNV", None, "FNV", "stock", "USD", False),
    ("FOX", "FOX", None, "FOX", "stock", "USD", False),
    ("FOXF", "FOXF", None, "FOXF", "stock", "USD", False),
    ("FRMI", "FRMI", None, "FRMI", "stock", "USD", False),
    ("FRT", "FRT", None, "FRT", "stock", "USD", False),
    ("FSLR", "FSLR", None, "FSLR", "stock", "USD", False),
    ("FSLY", "FSLY", None, "FSLY", "stock", "USD", False),
    ("FTAI", "FTAI", None, "FTAI", "stock", "USD", False),
    ("FTNT", "FTNT", None, "FTNT", "stock", "USD", False),
    ("FTS", "FTS", None, "FTS", "stock", "USD", False),
    ("FTV", "FTV", None, "FTV", "stock", "USD", False),
    ("FUTU", "FUTU", None, "FUTU", "stock", "USD", False),
    ("FVRR", "FVRR", None, "FVRR", "stock", "USD", False),
    ("FWONA", "FWONA", None, "FWONA", "stock", "USD", False),
    ("GAP", "GAP", None, "GAP", "stock", "USD", False),
    ("GBTC", "GBTC", None, "Grayscale Bitcoin Trust", "stock", "USD", False),
    ("GD", "GD", None, "GD", "stock", "USD", False),
    ("GDDY", "GDDY", None, "GDDY", "stock", "USD", False),
    ("GE", "GE", None, "GE", "stock", "USD", False),
    ("GEHC", "GEHC", None, "GEHC", "stock", "USD", False),
    ("GEN", "GEN", None, "GEN", "stock", "USD", False),
    ("GEV", "GEV", None, "GEV", "stock", "USD", False),
    ("GEVO", "GEVO", None, "GEVO", "stock", "USD", False),
    ("GFI", "GFI", None, "GFI", "stock", "USD", False),
    ("GFL", "GFL", None, "GFL", "stock", "USD", False),
    ("GFS", "GFS", None, "GFS", "stock", "USD", False),
    ("GGG", "GGG", None, "GGG", "stock", "USD", False),
    ("GH", "GH", None, "GH", "stock", "USD", False),
    ("GIB", "GIB", None, "GIB", "stock", "USD", False),
    ("GIL", "GIL", None, "GIL", "stock", "USD", False),
    ("GILD", "GILD", None, "Gilead Sciences", "stock", "USD", False),
    ("GIS", "GIS", None, "GIS", "stock", "USD", False),
    ("GL", "GL", None, "GL", "stock", "USD", False),
    ("GLPI", "GLPI", None, "GLPI", "stock", "USD", False),
    ("GLW", "GLW", None, "GLW", "stock", "USD", False),
    ("GLXY", "GLXY", None, "GLXY", "stock", "USD", False),
    ("GM", "GM", None, "GM", "stock", "USD", False),
    ("GMAB", "GMAB", None, "GMAB", "stock", "USD", False),
    ("GME", "GME", None, "GameStop Corp.", "stock", "USD", False),
    ("GMED", "GMED", None, "GMED", "stock", "USD", False),
    ("GNTX", "GNTX", None, "GNTX", "stock", "USD", False),
    ("GO", "GO", None, "GO", "stock", "USD", False),
    ("GOOGL", "GOOGL", None, "GOOGL", "stock", "USD", False),
    ("GOOS", "GOOS", None, "GOOS", "stock", "USD", False),
    ("GPC", "GPC", None, "GPC", "stock", "USD", False),
    ("GPK", "GPK", None, "GPK", "stock", "USD", False),
    ("GPN", "GPN", None, "GPN", "stock", "USD", False),
    ("GRMN", "GRMN", None, "GRMN", "stock", "USD", False),
    ("GS", "GS", None, "GS", "stock", "USD", False),
    ("GSK", "GSK", None, "GSK", "stock", "USD", False),
    ("GTLB", "GTLB", None, "GitLab Inc.", "stock", "USD", False),
    ("GWRE", "GWRE", None, "GWRE", "stock", "USD", False),
    ("GWW", "GWW", None, "GWW", "stock", "USD", False),
    ("HAL", "HAL", None, "HAL", "stock", "USD", False),
    ("HALO", "HALO", None, "HALO", "stock", "USD", False),
    ("HAS", "HAS", None, "HAS", "stock", "USD", False),
    ("HBAN", "HBAN", None, "HBAN", "stock", "USD", False),
    ("HCA", "HCA", None, "HCA", "stock", "USD", False),
    ("HD", "HD", None, "HD", "stock", "USD", False),
    ("HEI", "HEI", None, "HEI", "stock", "USD", False),
    ("HIG", "HIG", None, "HIG", "stock", "USD", False),
    ("HII", "HII", None, "HII", "stock", "USD", False),
    ("HIMS", "HIMS", None, "HIMS", "stock", "USD", False),
    ("HLF", "HLF", None, "HLF", "stock", "USD", False),
    ("HLI", "HLI", None, "HLI", "stock", "USD", False),
    ("HLT", "HLT", None, "HLT", "stock", "USD", False),
    ("HMC", "HMC", None, "HMC", "stock", "USD", False),
    ("HMY", "HMY", None, "HMY", "stock", "USD", False),
    ("HOG", "HOG", None, "HOG", "stock", "USD", False),
    ("HOLX", "HOLX", None, "HOLX", "stock", "USD", False),
    ("HON", "HON", None, "HON", "stock", "USD", False),
    ("HOOD", "HOOD", None, "Robinhood Markets", "stock", "USD", False),
    ("HPQ", "HPQ", None, "HPQ", "stock", "USD", False),
    ("HRB", "HRB", None, "HRB", "stock", "USD", False),
    ("HRL", "HRL", None, "HRL", "stock", "USD", False),
    ("HSIC", "HSIC", None, "HSIC", "stock", "USD", False),
    ("HST", "HST", None, "HST", "stock", "USD", False),
    ("HSY", "HSY", None, "HSY", "stock", "USD", False),
    ("HTGC", "HTGC", None, "HTGC", "stock", "USD", False),
    ("HTHT", "HTHT", None, "HTHT", "stock", "USD", False),
    ("HUBB", "HUBB", None, "HUBB", "stock", "USD", False),
    ("HUBS", "HUBS", None, "HUBS", "stock", "USD", False),
    ("HUM", "HUM", None, "HUM", "stock", "USD", False),
    ("HUN", "HUN", None, "HUN", "stock", "USD", False),
    ("HUT", "HUT", None, "HUT", "stock", "USD", False),
    ("HUYA", "HUYA", None, "HUYA", "stock", "USD", False),
    ("HWM", "HWM", None, "HWM", "stock", "USD", False),
    ("HXL", "HXL", None, "HXL", "stock", "USD", False),
    ("IAC", "IAC", None, "IAC", "stock", "USD", False),
    ("IBKR", "IBKR", None, "IBKR", "stock", "USD", False),
    ("IBM", "IBM", None, "IBM Corp.", "stock", "USD", False),
    ("IBN", "IBN", None, "IBN", "stock", "USD", False),
    ("ICE", "ICE", None, "ICE", "stock", "USD", False),
    ("ICLR", "ICLR", None, "ICLR", "stock", "USD", False),
    ("IDXX", "IDXX", None, "IDXX", "stock", "USD", False),
    ("IEX", "IEX", None, "IEX", "stock", "USD", False),
    ("IFF", "IFF", None, "IFF", "stock", "USD", False),
    ("IHG", "IHG", None, "IHG", "stock", "USD", False),
    ("ILMN", "ILMN", None, "ILMN", "stock", "USD", False),
    ("IMO", "IMO", None, "IMO", "stock", "USD", False),
    ("INCY", "INCY", None, "INCY", "stock", "USD", False),
    ("INFY", "INFY", None, "INFY", "stock", "USD", False),
    ("ING", "ING", None, "ING", "stock", "USD", False),
    ("INGR", "INGR", None, "INGR", "stock", "USD", False),
    ("INSM", "INSM", None, "INSM", "stock", "USD", False),
    ("INTC", "INTC", None, "INTC", "stock", "USD", False),
    ("INTU", "INTU", None, "INTU", "stock", "USD", False),
    ("INVH", "INVH", None, "INVH", "stock", "USD", False),
    ("IONQ", "IONQ", None, "IONQ", "stock", "USD", False),
    ("IONS", "IONS", None, "IONS", "stock", "USD", False),
    ("IOT", "IOT", None, "IOT", "stock", "USD", False),
    ("IP", "IP", None, "IP", "stock", "USD", False),
    ("IPGP", "IPGP", None, "IPGP", "stock", "USD", False),
    ("IQV", "IQV", None, "IQV", "stock", "USD", False),
    ("IR", "IR", None, "IR", "stock", "USD", False),
    ("IRDM", "IRDM", None, "IRDM", "stock", "USD", False),
    ("IREN", "IREN", None, "IREN", "stock", "USD", False),
    ("IRM", "IRM", None, "IRM", "stock", "USD", False),
    ("ISRG", "ISRG", None, "ISRG", "stock", "USD", False),
    ("IT", "IT", None, "IT", "stock", "USD", False),
    ("ITT", "ITT", None, "ITT", "stock", "USD", False),
    ("ITW", "ITW", None, "ITW", "stock", "USD", False),
    ("IVZ", "IVZ", None, "IVZ", "stock", "USD", False),
    ("IX", "IX", None, "IX", "stock", "USD", False),
    ("JAZZ", "JAZZ", None, "JAZZ", "stock", "USD", False),
    ("JBHT", "JBHT", None, "JBHT", "stock", "USD", False),
    ("JBL", "JBL", None, "JBL", "stock", "USD", False),
    ("JBLU", "JBLU", None, "JBLU", "stock", "USD", False),
    ("JCI", "JCI", None, "JCI", "stock", "USD", False),
    ("JD", "JD", None, "JD", "stock", "USD", False),
    ("JEF", "JEF", None, "JEF", "stock", "USD", False),
    ("JHG", "JHG", None, "JHG", "stock", "USD", False),
    ("JKHY", "JKHY", None, "JKHY", "stock", "USD", False),
    ("JKS", "JKS", None, "JKS", "stock", "USD", False),
    ("JLL", "JLL", None, "JLL", "stock", "USD", False),
    ("JNJ", "JNJ", None, "JNJ", "stock", "USD", False),
    ("JOBY", "JOBY", None, "JOBY", "stock", "USD", False),
    ("JPM", "JPM", None, "JPM", "stock", "USD", False),
    ("JUVE", "JUVE.MI", None, "Juventus FC", "stock", "EUR", False),
    ("KB", "KB", None, "KB", "stock", "USD", False),
    ("KBR", "KBR", None, "KBR", "stock", "USD", False),
    ("KC", "KC", None, "KC", "stock", "USD", False),
    ("KDP", "KDP", None, "KDP", "stock", "USD", False),
    ("KEP", "KEP", None, "KEP", "stock", "USD", False),
    ("KEX", "KEX", None, "KEX", "stock", "USD", False),
    ("KEY", "KEY", None, "KEY", "stock", "USD", False),
    ("KEYS", "KEYS", None, "KEYS", "stock", "USD", False),
    ("KGC", "KGC", None, "KGC", "stock", "USD", False),
    ("KHC", "KHC", None, "KHC", "stock", "USD", False),
    ("KIM", "KIM", None, "KIM", "stock", "USD", False),
    ("KKR", "KKR", None, "KKR", "stock", "USD", False),
    ("KLAC", "KLAC", None, "KLAC", "stock", "USD", False),
    ("KMB", "KMB", None, "KMB", "stock", "USD", False),
    ("KMI", "KMI", None, "KMI", "stock", "USD", False),
    ("KMT", "KMT", None, "KMT", "stock", "USD", False),
    ("KMX", "KMX", None, "KMX", "stock", "USD", False),
    ("KNX", "KNX", None, "KNX", "stock", "USD", False),
    ("KO", "KO", None, "KO", "stock", "USD", False),
    ("KR", "KR", None, "KR", "stock", "USD", False),
    ("KRC", "KRC", None, "KRC", "stock", "USD", False),
    ("KSPI", "KSPI", None, "KSPI", "stock", "USD", False),
    ("KSS", "KSS", None, "KSS", "stock", "USD", False),
    ("KTOS", "KTOS", None, "KTOS", "stock", "USD", False),
    ("KVUE", "KVUE", None, "KVUE", "stock", "USD", False),
    ("LAMR", "LAMR", None, "LAMR", "stock", "USD", False),
    ("LAUR", "LAUR", None, "LAUR", "stock", "USD", False),
    ("LAZ", "LAZ", None, "LAZ", "stock", "USD", False),
    ("LBTYA", "LBTYA", None, "LBTYA", "stock", "USD", False),
    ("LCID", "LCID", None, "LCID", "stock", "USD", False),
    ("LDOS", "LDOS", None, "LDOS", "stock", "USD", False),
    ("LEA", "LEA", None, "LEA", "stock", "USD", False),
    ("LECO", "LECO", None, "LECO", "stock", "USD", False),
    ("LEG", "LEG", None, "LEG", "stock", "USD", False),
    ("LEN", "LEN", None, "LEN", "stock", "USD", False),
    ("LEVI", "LEVI", None, "LEVI", "stock", "USD", False),
    ("LFUS", "LFUS", None, "LFUS", "stock", "USD", False),
    ("LH", "LH", None, "LH", "stock", "USD", False),
    ("LHX", "LHX", None, "LHX", "stock", "USD", False),
    ("LI", "LI", None, "LI", "stock", "USD", False),
    ("LII", "LII", None, "LII", "stock", "USD", False),
    ("LIN", "LIN", None, "LIN", "stock", "USD", False),
    ("LITE", "LITE", None, "LITE", "stock", "USD", False),
    ("LKQ", "LKQ", None, "LKQ", "stock", "USD", False),
    ("LLY", "LLY", None, "LLY", "stock", "USD", False),
    ("LMND", "LMND", None, "LMND", "stock", "USD", False),
    ("LMT", "LMT", None, "LMT", "stock", "USD", False),
    ("LNC", "LNC", None, "LNC", "stock", "USD", False),
    ("LNG", "LNG", None, "LNG", "stock", "USD", False),
    ("LNT", "LNT", None, "LNT", "stock", "USD", False),
    ("LOGI", "LOGI", None, "LOGI", "stock", "USD", False),
    ("LOW", "LOW", None, "LOW", "stock", "USD", False),
    ("LPLA", "LPLA", None, "LPLA", "stock", "USD", False),
    ("LPX", "LPX", None, "LPX", "stock", "USD", False),
    ("LRCX", "LRCX", None, "LRCX", "stock", "USD", False),
    ("LSCC", "LSCC", None, "LSCC", "stock", "USD", False),
    ("LULU", "LULU", None, "LULU", "stock", "USD", False),
    ("LUMN", "LUMN", None, "LUMN", "stock", "USD", False),
    ("LUV", "LUV", None, "Southwest Airlines", "stock", "USD", False),
    ("LVS", "LVS", None, "LVS", "stock", "USD", False),
    ("LYB", "LYB", None, "LYB", "stock", "USD", False),
    ("LYFT", "LYFT", None, "Lyft Inc.", "stock", "USD", False),
    ("LYV", "LYV", None, "LYV", "stock", "USD", False),
    ("LZ", "LZ", None, "LZ", "stock", "USD", False),
    ("MA", "MA", None, "MA", "stock", "USD", False),
    ("MAA", "MAA", None, "MAA", "stock", "USD", False),
    ("MAN", "MAN", None, "MAN", "stock", "USD", False),
    ("MAR", "MAR", None, "MAR", "stock", "USD", False),
    ("MARA", "MARA", None, "Marathon Digital", "stock", "USD", False),
    ("MAS", "MAS", None, "MAS", "stock", "USD", False),
    ("MASI", "MASI", None, "MASI", "stock", "USD", False),
    ("MAT", "MAT", None, "MAT", "stock", "USD", False),
    ("MBG", "MBG", None, "MBG", "stock", "USD", False),
    ("MBLY", "MBLY", None, "MBLY", "stock", "USD", False),
    ("MCD", "MCD", None, "MCD", "stock", "USD", False),
    ("MCHP", "MCHP", None, "MCHP", "stock", "USD", False),
    ("MCK", "MCK", None, "MCK", "stock", "USD", False),
    ("MCO", "MCO", None, "MCO", "stock", "USD", False),
    ("MDB", "MDB", None, "MDB", "stock", "USD", False),
    ("MDGL", "MDGL", None, "MDGL", "stock", "USD", False),
    ("MDLZ", "MDLZ", None, "MDLZ", "stock", "USD", False),
    ("MDT", "MDT", None, "MDT", "stock", "USD", False),
    ("MDU", "MDU", None, "MDU", "stock", "USD", False),
    ("MEDP", "MEDP", None, "MEDP", "stock", "USD", False),
    ("MELI", "MELI", None, "MercadoLibre", "stock", "USD", False),
    ("MET", "MET", None, "MET", "stock", "USD", False),
    ("META", "META", None, "Meta Platforms", "stock", "USD", False),
    ("MFC", "MFC", None, "MFC", "stock", "USD", False),
    ("MGA", "MGA", None, "MGA", "stock", "USD", False),
    ("MGM", "MGM", None, "MGM", "stock", "USD", False),
    ("MHK", "MHK", None, "MHK", "stock", "USD", False),
    ("MIDD", "MIDD", None, "MIDD", "stock", "USD", False),
    ("MKC", "MKC", None, "MKC", "stock", "USD", False),
    ("MKL", "MKL", None, "MKL", "stock", "USD", False),
    ("MLCO", "MLCO", None, "MLCO", "stock", "USD", False),
    ("MLI", "MLI", None, "MLI", "stock", "USD", False),
    ("MLM", "MLM", None, "MLM", "stock", "USD", False),
    ("MMC", "MMC", None, "MMC", "stock", "USD", False),
    ("MMSI", "MMSI", None, "MMSI", "stock", "USD", False),
    ("MMYT", "MMYT", None, "MMYT", "stock", "USD", False),
    ("MNDY", "MNDY", None, "MNDY", "stock", "USD", False),
    ("MNST", "MNST", None, "MNST", "stock", "USD", False),
    ("MO", "MO", None, "MO", "stock", "USD", False),
    ("MOS", "MOS", None, "MOS", "stock", "USD", False),
    ("MP", "MP", None, "MP", "stock", "USD", False),
    ("MPC", "MPC", None, "MPC", "stock", "USD", False),
    ("MPLX", "MPLX", None, "MPLX", "stock", "USD", False),
    ("MPWR", "MPWR", None, "MPWR", "stock", "USD", False),
    ("MRCY", "MRCY", None, "MRCY", "stock", "USD", False),
    ("MRK", "MRK", None, "MRK", "stock", "USD", False),
    ("MRNA", "MRNA", None, "Moderna Inc.", "stock", "USD", False),
    ("MRVL", "MRVL", None, "MRVL", "stock", "USD", False),
    ("MS", "MS", None, "MS", "stock", "USD", False),
    ("MSCI", "MSCI", None, "MSCI", "stock", "USD", False),
    ("MSFT", "MSFT", None, "MSFT", "stock", "USD", False),
    ("MSGS", "MSGS", None, "MSGS", "stock", "USD", False),
    ("MSI", "MSI", None, "MSI", "stock", "USD", False),
    ("MSM", "MSM", None, "MSM", "stock", "USD", False),
    ("MSTR", "MSTR", None, "MSTR", "stock", "USD", False),
    ("MT", "MT", None, "MT", "stock", "USD", False),
    ("MTB", "MTB", None, "MTB", "stock", "USD", False),
    ("MTCH", "MTCH", None, "MTCH", "stock", "USD", False),
    ("MTD", "MTD", None, "MTD", "stock", "USD", False),
    ("MTG", "MTG", None, "MTG", "stock", "USD", False),
    ("MTSI", "MTSI", None, "MTSI", "stock", "USD", False),
    ("MTZ", "MTZ", None, "MTZ", "stock", "USD", False),
    ("MU", "MU", None, "MU", "stock", "USD", False),
    ("MUFG", "MUFG", None, "MUFG", "stock", "USD", False),
    ("NBIX", "NBIX", None, "NBIX", "stock", "USD", False),
    ("NCLH", "NCLH", None, "Norwegian Cruise Line", "stock", "USD", False),
    ("NDAQ", "NDAQ", None, "NDAQ", "stock", "USD", False),
    ("NDSN", "NDSN", None, "NDSN", "stock", "USD", False),
    ("NEE", "NEE", None, "NEE", "stock", "USD", False),
    ("NEM", "NEM", None, "NEM", "stock", "USD", False),
    ("NET", "NET", None, "NET", "stock", "USD", False),
    ("NEU", "NEU", None, "NEU", "stock", "USD", False),
    ("NFG", "NFG", None, "NFG", "stock", "USD", False),
    ("NFLX", "NFLX", None, "NFLX", "stock", "USD", False),
    ("NGG", "NGG", None, "NGG", "stock", "USD", False),
    ("NI", "NI", None, "NI", "stock", "USD", False),
    ("NIO", "NIO", None, "NIO", "stock", "USD", False),
    ("NKE", "NKE", None, "NKE", "stock", "USD", False),
    ("NLY", "NLY", None, "NLY", "stock", "USD", False),
    ("NOC", "NOC", None, "NOC", "stock", "USD", False),
    ("NOV", "NOV", None, "NOV", "stock", "USD", False),
    ("NOW", "NOW", None, "NOW", "stock", "USD", False),
    ("NRG", "NRG", None, "NRG", "stock", "USD", False),
    ("NSC", "NSC", None, "NSC", "stock", "USD", False),
    ("NTAP", "NTAP", None, "NTAP", "stock", "USD", False),
    ("NTES", "NTES", None, "NTES", "stock", "USD", False),
    ("NTNX", "NTNX", None, "NTNX", "stock", "USD", False),
    ("NTR", "NTR", None, "NTR", "stock", "USD", False),
    ("NTRA", "NTRA", None, "NTRA", "stock", "USD", False),
    ("NTRS", "NTRS", None, "NTRS", "stock", "USD", False),
    ("NU", "NU", None, "NU", "stock", "USD", False),
    ("NUE", "NUE", None, "NUE", "stock", "USD", False),
    ("NVDA", "NVDA", None, "NVDA", "stock", "USD", False),
    ("NVO", "NVO", None, "NVO", "stock", "USD", False),
    ("NVR", "NVR", None, "NVR", "stock", "USD", False),
    ("NVS", "NVS", None, "NVS", "stock", "USD", False),
    ("NVT", "NVT", None, "NVT", "stock", "USD", False),
    ("NWG", "NWG", None, "NWG", "stock", "USD", False),
    ("NWL", "NWL", None, "NWL", "stock", "USD", False),
    ("NWSA", "NWSA", None, "NWSA", "stock", "USD", False),
    ("NXPI", "NXPI", None, "NXPI", "stock", "USD", False),
    ("NXT", "NXT", None, "NXT", "stock", "USD", False),
    ("OC", "OC", None, "OC", "stock", "USD", False),
    ("ODFL", "ODFL", None, "ODFL", "stock", "USD", False),
    ("OGE", "OGE", None, "OGE", "stock", "USD", False),
    ("OHI", "OHI", None, "OHI", "stock", "USD", False),
    ("OKE", "OKE", None, "OKE", "stock", "USD", False),
    ("OKLO", "OKLO", None, "OKLO", "stock", "USD", False),
    ("OKTA", "OKTA", None, "OKTA", "stock", "USD", False),
    ("OMC", "OMC", None, "OMC", "stock", "USD", False),
    ("ON", "ON", None, "ON", "stock", "USD", False),
    ("ONC", "ONC", None, "ONC", "stock", "USD", False),
    ("ONON", "ONON", None, "ONON", "stock", "USD", False),
    ("OPEN", "OPEN", None, "OPEN", "stock", "USD", False),
    ("ORCL", "ORCL", None, "ORCL", "stock", "USD", False),
    ("ORI", "ORI", None, "ORI", "stock", "USD", False),
    ("ORLY", "ORLY", None, "ORLY", "stock", "USD", False),
    ("OSK", "OSK", None, "OSK", "stock", "USD", False),
    ("OTEX", "OTEX", None, "OTEX", "stock", "USD", False),
    ("OTIS", "OTIS", None, "OTIS", "stock", "USD", False),
    ("OVV", "OVV", None, "OVV", "stock", "USD", False),
    ("OWL", "OWL", None, "OWL", "stock", "USD", False),
    ("OXY", "OXY", None, "OXY", "stock", "USD", False),
    ("P911", "P911", None, "P911", "stock", "USD", False),
    ("PAA", "PAA", None, "PAA", "stock", "USD", False),
    ("PAAS", "PAAS", None, "PAAS", "stock", "USD", False),
    ("PAGS", "PAGS", None, "PAGS", "stock", "USD", False),
    ("PANW", "PANW", None, "PANW", "stock", "USD", False),
    ("PATH", "PATH", None, "PATH", "stock", "USD", False),
    ("PAYC", "PAYC", None, "PAYC", "stock", "USD", False),
    ("PAYX", "PAYX", None, "PAYX", "stock", "USD", False),
    ("PB", "PB", None, "PB", "stock", "USD", False),
    ("PBA", "PBA", None, "PBA", "stock", "USD", False),
    ("PBR", "PBR", None, "PBR", "stock", "USD", False),
    ("PCAR", "PCAR", None, "PCAR", "stock", "USD", False),
    ("PCG", "PCG", None, "PCG", "stock", "USD", False),
    ("PCOR", "PCOR", None, "PCOR", "stock", "USD", False),
    ("PDD", "PDD", None, "PDD", "stock", "USD", False),
    ("PEG", "PEG", None, "PEG", "stock", "USD", False),
    ("PENN", "PENN", None, "PENN", "stock", "USD", False),
    ("PEP", "PEP", None, "PEP", "stock", "USD", False),
    ("PFE", "PFE", None, "PFE", "stock", "USD", False),
    ("PFG", "PFG", None, "PFG", "stock", "USD", False),
    ("PFGC", "PFGC", None, "PFGC", "stock", "USD", False),
    ("PG", "PG", None, "PG", "stock", "USD", False),
    ("PGR", "PGR", None, "PGR", "stock", "USD", False),
    ("PH", "PH", None, "PH", "stock", "USD", False),
    ("PHG", "PHG", None, "PHG", "stock", "USD", False),
    ("PHM", "PHM", None, "PHM", "stock", "USD", False),
    ("PII", "PII", None, "PII", "stock", "USD", False),
    ("PINS", "PINS", None, "Pinterest Inc.", "stock", "USD", False),
    ("PKG", "PKG", None, "PKG", "stock", "USD", False),
    ("PKX", "PKX", None, "PKX", "stock", "USD", False),
    ("PLD", "PLD", None, "PLD", "stock", "USD", False),
    ("PLNT", "PLNT", None, "PLNT", "stock", "USD", False),
    ("PLTR", "PLTR", None, "PLTR", "stock", "USD", False),
    ("PM", "PM", None, "PM", "stock", "USD", False),
    ("PNC", "PNC", None, "PNC", "stock", "USD", False),
    ("PNR", "PNR", None, "PNR", "stock", "USD", False),
    ("PODD", "PODD", None, "PODD", "stock", "USD", False),
    ("POOL", "POOL", None, "POOL", "stock", "USD", False),
    ("PPG", "PPG", None, "PPG", "stock", "USD", False),
    ("PPL", "PPL", None, "PPL", "stock", "USD", False),
    ("PR", "PR", None, "PR", "stock", "USD", False),
    ("PRU", "PRU", None, "PRU", "stock", "USD", False),
    ("PSA", "PSA", None, "PSA", "stock", "USD", False),
    ("PSFE", "PSFE", None, "PSFE", "stock", "USD", False),
    ("PSKY", "PSKY", None, "PSKY", "stock", "USD", False),
    ("PSNY", "PSNY", None, "PSNY", "stock", "USD", False),
    ("PSTG", "PSTG", None, "PSTG", "stock", "USD", False),
    ("PSX", "PSX", None, "PSX", "stock", "USD", False),
    ("PTC", "PTC", None, "PTC", "stock", "USD", False),
    ("PTON", "PTON", None, "PTON", "stock", "USD", False),
    ("PUK", "PUK", None, "PUK", "stock", "USD", False),
    ("PVH", "PVH", None, "PVH Corp.", "stock", "USD", False),
    ("PWR", "PWR", None, "PWR", "stock", "USD", False),
    ("PYPL", "PYPL", None, "PYPL", "stock", "USD", False),
    ("QCOM", "QCOM", None, "QCOM", "stock", "USD", False),
    ("QDEL", "QDEL", None, "QDEL", "stock", "USD", False),
    ("QGEN", "QGEN", None, "QGEN", "stock", "USD", False),
    ("QRVO", "QRVO", None, "QRVO", "stock", "USD", False),
    ("QS", "QS", None, "QS", "stock", "USD", False),
    ("QSR", "QSR", None, "QSR", "stock", "USD", False),
    ("QXO", "QXO", None, "QXO", "stock", "USD", False),
    ("RACE", "RACE", None, "RACE", "stock", "USD", False),
    ("RBA", "RBA", None, "RBA", "stock", "USD", False),
    ("RBC", "RBC", None, "RBC", "stock", "USD", False),
    ("RBLX", "RBLX", None, "RBLX", "stock", "USD", False),
    ("RBRK", "RBRK", None, "RBRK", "stock", "USD", False),
    ("RCI", "RCI", None, "RCI", "stock", "USD", False),
    ("RCL", "RCL", None, "Royal Caribbean Cruises", "stock", "USD", False),
    ("RDDT", "RDDT", None, "RDDT", "stock", "USD", False),
    ("RDN", "RDN", None, "RDN", "stock", "USD", False),
    ("RDY", "RDY", None, "RDY", "stock", "USD", False),
    ("REG", "REG", None, "REG", "stock", "USD", False),
    ("REGN", "REGN", None, "REGN", "stock", "USD", False),
    ("RELX", "RELX", None, "RELX", "stock", "USD", False),
    ("REP", "REP.MC", None, "Repsol SA", "stock", "EUR", False),
    ("RF", "RF", None, "RF", "stock", "USD", False),
    ("RGA", "RGA", None, "RGA", "stock", "USD", False),
    ("RGLD", "RGLD", None, "RGLD", "stock", "USD", False),
    ("RGTI", "RGTI", None, "RGTI", "stock", "USD", False),
    ("RH", "RH", None, "RH", "stock", "USD", False),
    ("RHI", "RHI", None, "RHI", "stock", "USD", False),
    ("RHM", "RHM", None, "RHM", "stock", "USD", False),
    ("RIG", "RIG", None, "RIG", "stock", "USD", False),
    ("RIO", "RIO", None, "RIO", "stock", "USD", False),
    ("RIOT", "RIOT", None, "RIOT", "stock", "USD", False),
    ("RITM", "RITM", None, "RITM", "stock", "USD", False),
    ("RIVN", "RIVN", None, "RIVN", "stock", "USD", False),
    ("RJF", "RJF", None, "RJF", "stock", "USD", False),
    ("RKLB", "RKLB", None, "RKLB", "stock", "USD", False),
    ("RKT", "RKT", None, "RKT", "stock", "USD", False),
    ("RL", "RL", None, "RL", "stock", "USD", False),
    ("RMBS", "RMBS", None, "RMBS", "stock", "USD", False),
    ("RMD", "RMD", None, "RMD", "stock", "USD", False),
    ("RNO", "RNO.PA", None, "Renault SA", "stock", "EUR", False),
    ("RNR", "RNR", None, "RNR", "stock", "USD", False),
    ("ROIV", "ROIV", None, "ROIV", "stock", "USD", False),
    ("ROK", "ROK", None, "ROK", "stock", "USD", False),
    ("ROKU", "ROKU", None, "ROKU", "stock", "USD", False),
    ("ROL", "ROL", None, "ROL", "stock", "USD", False),
    ("ROP", "ROP", None, "ROP", "stock", "USD", False),
    ("ROST", "ROST", None, "ROST", "stock", "USD", False),
    ("RPD", "RPD", None, "RPD", "stock", "USD", False),
    ("RPM", "RPM", None, "RPM", "stock", "USD", False),
    ("RPRX", "RPRX", None, "RPRX", "stock", "USD", False),
    ("RRX", "RRX", None, "RRX", "stock", "USD", False),
    ("RS", "RS", None, "RS", "stock", "USD", False),
    ("RSG", "RSG", None, "RSG", "stock", "USD", False),
    ("RTO", "RTO", None, "RTO", "stock", "USD", False),
    ("RUN", "RUN", None, "RUN", "stock", "USD", False),
    ("RVMD", "RVMD", None, "RVMD", "stock", "USD", False),
    ("RY", "RY", None, "RY", "stock", "USD", False),
    ("RYAAY", "RYAAY", None, "Ryanair Holdings", "stock", "USD", False),
    ("RYAN", "RYAN", None, "RYAN", "stock", "USD", False),
    ("RYN", "RYN", None, "RYN", "stock", "USD", False),
    ("SAIL", "SAIL", None, "SAIL", "stock", "USD", False),
    ("SAP", "SAP", None, "SAP SE", "stock", "USD", False),
    ("SBAC", "SBAC", None, "SBAC", "stock", "USD", False),
    ("SBRA", "SBRA", None, "SBRA", "stock", "USD", False),
    ("SBS", "SBS", None, "SBS", "stock", "USD", False),
    ("SBSW", "SBSW", None, "SBSW", "stock", "USD", False),
    ("SBUX", "SBUX", None, "SBUX", "stock", "USD", False),
    ("SCCO", "SCCO", None, "SCCO", "stock", "USD", False),
    ("SCHW", "SCHW", None, "SCHW", "stock", "USD", False),
    ("SCI", "SCI", None, "SCI", "stock", "USD", False),
    ("SDGR", "SDGR", None, "SDGR", "stock", "USD", False),
    ("SE", "SE", None, "SE", "stock", "USD", False),
    ("SEDG", "SEDG", None, "SEDG", "stock", "USD", False),
    ("SEE", "SEE", None, "SEE", "stock", "USD", False),
    ("SEIC", "SEIC", None, "SEIC", "stock", "USD", False),
    ("SF", "SF", None, "SF", "stock", "USD", False),
    ("SGI", "SGI", None, "SGI", "stock", "USD", False),
    ("SHAK", "SHAK", None, "SHAK", "stock", "USD", False),
    ("SHC", "SHC", None, "SHC", "stock", "USD", False),
    ("SHEL", "SHEL", None, "SHEL", "stock", "USD", False),
    ("SHG", "SHG", None, "SHG", "stock", "USD", False),
    ("SHOP", "SHOP", None, "SHOP", "stock", "USD", False),
    ("SHW", "SHW", None, "SHW", "stock", "USD", False),
    ("SIE", "SIE.DE", None, "Siemens AG", "stock", "EUR", False),
    ("SJM", "SJM", None, "SJM", "stock", "USD", False),
    ("SLAB", "SLAB", None, "SLAB", "stock", "USD", False),
    ("SLB", "SLB", None, "SLB", "stock", "USD", False),
    ("SLF", "SLF", None, "SLF", "stock", "USD", False),
    ("SLG", "SLG", None, "SLG", "stock", "USD", False),
    ("SLGN", "SLGN", None, "SLGN", "stock", "USD", False),
    ("SLM", "SLM", None, "SLM", "stock", "USD", False),
    ("SMCI", "SMCI", None, "SMCI", "stock", "USD", False),
    ("SMFG", "SMFG", None, "SMFG", "stock", "USD", False),
    ("SMG", "SMG", None, "SMG", "stock", "USD", False),
    ("SMMT", "SMMT", None, "SMMT", "stock", "USD", False),
    ("SMR", "SMR", None, "SMR", "stock", "USD", False),
    ("SN", "SN", None, "SN", "stock", "USD", False),
    ("SNA", "SNA", None, "SNA", "stock", "USD", False),
    ("SNAP", "SNAP", None, "SNAP", "stock", "USD", False),
    ("SNDK", "SNDK", None, "SNDK", "stock", "USD", False),
    ("SNN", "SNN", None, "SNN", "stock", "USD", False),
    ("SNOW", "SNOW", None, "SNOW", "stock", "USD", False),
    ("SNPS", "SNPS", None, "SNPS", "stock", "USD", False),
    ("SNX", "SNX", None, "SNX", "stock", "USD", False),
    ("SNY", "SNY", None, "SNY", "stock", "USD", False),
    ("SO", "SO", None, "SO", "stock", "USD", False),
    ("SOFI", "SOFI", None, "SOFI", "stock", "USD", False),
    ("SOLV", "SOLV", None, "SOLV", "stock", "USD", False),
    ("SON", "SON", None, "SON", "stock", "USD", False),
    ("SONO", "SONO", None, "SONO", "stock", "USD", False),
    ("SONY", "SONY", None, "SONY", "stock", "USD", False),
    ("SPB", "SPB", None, "SPB", "stock", "USD", False),
    ("SPCE", "SPCE", None, "Virgin Galactic Holdings", "stock", "USD", False),
    ("SPG", "SPG", None, "SPG", "stock", "USD", False),
    ("SPGI", "SPGI", None, "SPGI", "stock", "USD", False),
    ("SPOT", "SPOT", None, "SPOT", "stock", "USD", False),
    ("SPXC", "SPXC", None, "SPXC", "stock", "USD", False),
    ("SQM", "SQM", None, "Sociedad Quimica y Minera", "stock", "USD", False),
    ("SRAD", "SRAD", None, "SRAD", "stock", "USD", False),
    ("SRE", "SRE", None, "SRE", "stock", "USD", False),
    ("SSL", "SSL", None, "SSL", "stock", "USD", False),
    ("SSNC", "SSNC", None, "SSNC", "stock", "USD", False),
    ("STE", "STE", None, "STE", "stock", "USD", False),
    ("STLA", "STLA", None, "STLA", "stock", "USD", False),
    ("STLD", "STLD", None, "STLD", "stock", "USD", False),
    ("STM", "STM", None, "STM", "stock", "USD", False),
    ("STN", "STN", None, "STN", "stock", "USD", False),
    ("STNE", "STNE", None, "STNE", "stock", "USD", False),
    ("STRL", "STRL", None, "STRL", "stock", "USD", False),
    ("STT", "STT", None, "STT", "stock", "USD", False),
    ("STZ", "STZ", None, "STZ", "stock", "USD", False),
    ("SU", "SU", None, "SU", "stock", "USD", False),
    ("SUI", "SUI", None, "SUI", "stock", "USD", False),
    ("SW", "SW", None, "SW", "stock", "USD", False),
    ("SWK", "SWK", None, "SWK", "stock", "USD", False),
    ("SWKS", "SWKS", None, "SWKS", "stock", "USD", False),
    ("SYF", "SYF", None, "SYF", "stock", "USD", False),
    ("SYK", "SYK", None, "SYK", "stock", "USD", False),
    ("SYM", "SYM", None, "SYM", "stock", "USD", False),
    ("SYY", "SYY", None, "SYY", "stock", "USD", False),
    ("TAK", "TAK", None, "TAK", "stock", "USD", False),
    ("TAL", "TAL", None, "TAL", "stock", "USD", False),
    ("TAP", "TAP", None, "TAP", "stock", "USD", False),
    ("TCOM", "TCOM", None, "TCOM", "stock", "USD", False),
    ("TD", "TD", None, "TD", "stock", "USD", False),
    ("TDG", "TDG", None, "TDG", "stock", "USD", False),
    ("TDY", "TDY", None, "TDY", "stock", "USD", False),
    ("TEAM", "TEAM", None, "TEAM", "stock", "USD", False),
    ("TECK", "TECK", None, "TECK", "stock", "USD", False),
    ("TEL", "TEL", None, "TEL", "stock", "USD", False),
    ("TEM", "TEM", None, "TEM", "stock", "USD", False),
    ("TER", "TER", None, "TER", "stock", "USD", False),
    ("TEVA", "TEVA", None, "TEVA", "stock", "USD", False),
    ("TFC", "TFC", None, "TFC", "stock", "USD", False),
    ("TFX", "TFX", None, "TFX", "stock", "USD", False),
    ("TGT", "TGT", None, "TGT", "stock", "USD", False),
    ("TGTX", "TGTX", None, "TGTX", "stock", "USD", False),
    ("THC", "THC", None, "THC", "stock", "USD", False),
    ("THO", "THO", None, "THO", "stock", "USD", False),
    ("TIMB", "TIMB", None, "TIMB", "stock", "USD", False),
    ("TJX", "TJX", None, "TJX", "stock", "USD", False),
    ("TKO", "TKO", None, "TKO", "stock", "USD", False),
    ("TLK", "TLK", None, "TLK", "stock", "USD", False),
    ("TLN", "TLN", None, "TLN", "stock", "USD", False),
    ("TLRY", "TLRY", None, "TLRY", "stock", "USD", False),
    ("TM", "TM", None, "TM", "stock", "USD", False),
    ("TME", "TME", None, "TME", "stock", "USD", False),
    ("TMO", "TMO", None, "TMO", "stock", "USD", False),
    ("TMUS", "TMUS", None, "TMUS", "stock", "USD", False),
    ("TNDM", "TNDM", None, "TNDM", "stock", "USD", False),
    ("TNL", "TNL", None, "TNL", "stock", "USD", False),
    ("TOL", "TOL", None, "TOL", "stock", "USD", False),
    ("TOST", "TOST", None, "TOST", "stock", "USD", False),
    ("TPG", "TPG", None, "TPG", "stock", "USD", False),
    ("TPL", "TPL", None, "TPL", "stock", "USD", False),
    ("TPR", "TPR", None, "TPR", "stock", "USD", False),
    ("TRGP", "TRGP", None, "TRGP", "stock", "USD", False),
    ("TRI", "TRI", None, "TRI", "stock", "USD", False),
    ("TRIP", "TRIP", None, "TRIP", "stock", "USD", False),
    ("TRMB", "TRMB", None, "TRMB", "stock", "USD", False),
    ("TRN", "TRN", None, "TRN", "stock", "USD", False),
    ("TROW", "TROW", None, "TROW", "stock", "USD", False),
    ("TRP", "TRP", None, "TRP", "stock", "USD", False),
    ("TRU", "TRU", None, "TRU", "stock", "USD", False),
    ("TRV", "TRV", None, "TRV", "stock", "USD", False),
    ("TS", "TS", None, "TS", "stock", "USD", False),
    ("TSCO", "TSCO", None, "TSCO", "stock", "USD", False),
    ("TSEM", "TSEM", None, "TSEM", "stock", "USD", False),
    ("TSLA", "TSLA", None, "TSLA", "stock", "USD", False),
    ("TSM", "TSM", None, "TSM", "stock", "USD", False),
    ("TSN", "TSN", None, "TSN", "stock", "USD", False),
    ("TT", "TT", None, "TT", "stock", "USD", False),
    ("TTC", "TTC", None, "TTC", "stock", "USD", False),
    ("TTD", "TTD", None, "TTD", "stock", "USD", False),
    ("TTWO", "TTWO", None, "TTWO", "stock", "USD", False),
    ("TU", "TU", None, "TU", "stock", "USD", False),
    ("TUI", "TUI", None, "TUI", "stock", "USD", False),
    ("TW", "TW", None, "TW", "stock", "USD", False),
    ("TWLO", "TWLO", None, "TWLO", "stock", "USD", False),
    ("TXN", "TXN", None, "TXN", "stock", "USD", False),
    ("TXT", "TXT", None, "TXT", "stock", "USD", False),
    ("TYL", "TYL", None, "TYL", "stock", "USD", False),
    ("UAA", "UAA", None, "UAA", "stock", "USD", False),
    ("UAL", "UAL", None, "UAL", "stock", "USD", False),
    ("UBER", "UBER", None, "Uber Technologies", "stock", "USD", False),
    ("UBS", "UBS", None, "UBS", "stock", "USD", False),
    ("UDR", "UDR", None, "UDR", "stock", "USD", False),
    ("UGI", "UGI", None, "UGI", "stock", "USD", False),
    ("UHS", "UHS", None, "UHS", "stock", "USD", False),
    ("UI", "UI", None, "UI", "stock", "USD", False),
    ("UL", "UL", None, "UL", "stock", "USD", False),
    ("ULS", "ULS", None, "ULS", "stock", "USD", False),
    ("ULTA", "ULTA", None, "ULTA", "stock", "USD", False),
    ("UNH", "UNH", None, "UNH", "stock", "USD", False),
    ("UNM", "UNM", None, "UNM", "stock", "USD", False),
    ("UNP", "UNP", None, "UNP", "stock", "USD", False),
    ("UPS", "UPS", None, "UPS", "stock", "USD", False),
    ("URI", "URI", None, "URI", "stock", "USD", False),
    ("USB", "USB", None, "USB", "stock", "USD", False),
    ("USFD", "USFD", None, "USFD", "stock", "USD", False),
    ("UTHR", "UTHR", None, "UTHR", "stock", "USD", False),
    ("VALE", "VALE", None, "VALE", "stock", "USD", False),
    ("VC", "VC", None, "VC", "stock", "USD", False),
    ("VCYT", "VCYT", None, "VCYT", "stock", "USD", False),
    ("VEEV", "VEEV", None, "VEEV", "stock", "USD", False),
    ("VFC", "VFC", None, "VFC", "stock", "USD", False),
    ("VFS", "VFS", None, "VFS", "stock", "USD", False),
    ("VICI", "VICI", None, "VICI", "stock", "USD", False),
    ("VIK", "VIK", None, "VIK", "stock", "USD", False),
    ("VIRT", "VIRT", None, "VIRT", "stock", "USD", False),
    ("VIV", "VIV", None, "VIV", "stock", "USD", False),
    ("VLO", "VLO", None, "VLO", "stock", "USD", False),
    ("VLTO", "VLTO", None, "VLTO", "stock", "USD", False),
    ("VMC", "VMC", None, "VMC", "stock", "USD", False),
    ("VMI", "VMI", None, "VMI", "stock", "USD", False),
    ("VNO", "VNO", None, "VNO", "stock", "USD", False),
    ("VNOM", "VNOM", None, "VNOM", "stock", "USD", False),
    ("VOD", "VOD", None, "VOD", "stock", "USD", False),
    ("VOW", "VOW", None, "VOW", "stock", "USD", False),
    ("VRSK", "VRSK", None, "VRSK", "stock", "USD", False),
    ("VRSN", "VRSN", None, "VRSN", "stock", "USD", False),
    ("VRT", "VRT", None, "VRT", "stock", "USD", False),
    ("VRTX", "VRTX", None, "VRTX", "stock", "USD", False),
    ("VST", "VST", None, "VST", "stock", "USD", False),
    ("VTR", "VTR", None, "VTR", "stock", "USD", False),
    ("VTRS", "VTRS", None, "VTRS", "stock", "USD", False),
    ("VYX", "VYX", None, "VYX", "stock", "USD", False),
    ("VZ", "VZ", None, "VZ", "stock", "USD", False),
    ("WAB", "WAB", None, "WAB", "stock", "USD", False),
    ("WAT", "WAT", None, "WAT", "stock", "USD", False),
    ("WB", "WB", None, "WB", "stock", "USD", False),
    ("WBD", "WBD", None, "WBD", "stock", "USD", False),
    ("WBS", "WBS", None, "WBS", "stock", "USD", False),
    ("WCC", "WCC", None, "WCC", "stock", "USD", False),
    ("WCN", "WCN", None, "WCN", "stock", "USD", False),
    ("WDAY", "WDAY", None, "WDAY", "stock", "USD", False),
    ("WDC", "WDC", None, "WDC", "stock", "USD", False),
    ("WDS", "WDS", None, "WDS", "stock", "USD", False),
    ("WEC", "WEC", None, "WEC", "stock", "USD", False),
    ("WEED", "WEED", None, "WEED", "stock", "USD", False),
    ("WELL", "WELL", None, "WELL", "stock", "USD", False),
    ("WEN", "WEN", None, "WEN", "stock", "USD", False),
    ("WES", "WES", None, "WES", "stock", "USD", False),
    ("WEX", "WEX", None, "WEX", "stock", "USD", False),
    ("WF", "WF", None, "WF", "stock", "USD", False),
    ("WFC", "WFC", None, "WFC", "stock", "USD", False),
    ("WHR", "WHR", None, "WHR", "stock", "USD", False),
    ("WLK", "WLK", None, "WLK", "stock", "USD", False),
    ("WM", "WM", None, "WM", "stock", "USD", False),
    ("WMB", "WMB", None, "WMB", "stock", "USD", False),
    ("WMG", "WMG", None, "WMG", "stock", "USD", False),
    ("WMS", "WMS", None, "WMS", "stock", "USD", False),
    ("WPC", "WPC", None, "WPC", "stock", "USD", False),
    ("WPM", "WPM", None, "WPM", "stock", "USD", False),
    ("WRB", "WRB", None, "WRB", "stock", "USD", False),
    ("WSM", "WSM", None, "WSM", "stock", "USD", False),
    ("WSO", "WSO", None, "WSO", "stock", "USD", False),
    ("WST", "WST", None, "WST", "stock", "USD", False),
    ("WTRG", "WTRG", None, "WTRG", "stock", "USD", False),
    ("WTW", "WTW", None, "WTW", "stock", "USD", False),
    ("WU", "WU", None, "WU", "stock", "USD", False),
    ("WWD", "WWD", None, "WWD", "stock", "USD", False),
    ("WY", "WY", None, "WY", "stock", "USD", False),
    ("WYNN", "WYNN", None, "Wynn Resorts", "stock", "USD", False),
    ("XEL", "XEL", None, "XEL", "stock", "USD", False),
    ("XOM", "XOM", None, "XOM", "stock", "USD", False),
    ("XP", "XP", None, "XP", "stock", "USD", False),
    ("XPEV", "XPEV", None, "XPEV", "stock", "USD", False),
    ("XPO", "XPO", None, "XPO", "stock", "USD", False),
    ("XRAY", "XRAY", None, "XRAY", "stock", "USD", False),
    ("XYL", "XYL", None, "XYL", "stock", "USD", False),
    ("XYZ", "XYZ", None, "XYZ", "stock", "USD", False),
    ("YMM", "YMM", None, "YMM", "stock", "USD", False),
    ("YOU", "YOU", None, "YOU", "stock", "USD", False),
    ("YPF", "YPF", None, "YPF", "stock", "USD", False),
    ("YUM", "YUM", None, "YUM", "stock", "USD", False),
    ("YUMC", "YUMC", None, "YUMC", "stock", "USD", False),
    ("ZBH", "ZBH", None, "ZBH", "stock", "USD", False),
    ("ZBRA", "ZBRA", None, "ZBRA", "stock", "USD", False),
    ("ZD", "ZD", None, "ZD", "stock", "USD", False),
    ("ZETA", "ZETA", None, "ZETA", "stock", "USD", False),
    ("ZION", "ZION", None, "ZION", "stock", "USD", False),
    ("ZM", "ZM", None, "ZM", "stock", "USD", False),
    ("ZS", "ZS", None, "ZS", "stock", "USD", False),
    ("ZTO", "ZTO", None, "ZTO", "stock", "USD", False),
    ("ZTS", "ZTS", None, "ZTS", "stock", "USD", False),
    ("ZYME", "ZYME", None, "ZYME", "stock", "USD", False),
    ("ABC", "ABC", None, "ABC", "stock", "USD", False),
    ("ADT", "ADT", None, "ADT", "stock", "USD", False),
    ("ADV", "ADV", None, "ADV", "stock", "USD", False),
    ("AGEN", "AGEN", None, "AGEN", "stock", "USD", False),
    ("AM", "AM", None, "AM", "stock", "USD", False),
    ("AMCR", "AMCR", None, "AMCR", "stock", "USD", False),
    ("ARKO", "ARKO", None, "ARKO", "stock", "USD", False),
    ("AROC", "AROC", None, "AROC", "stock", "USD", False),
    ("AVAH", "AVAH", None, "AVAH", "stock", "USD", False),
    ("AVPT", "AVPT", None, "AVPT", "stock", "USD", False),
    ("AXL", "AXL", None, "AXL", "stock", "USD", False),
    ("BGC", "BGC", None, "BGC", "stock", "USD", False),
    ("BKD", "BKD", None, "BKD", "stock", "USD", False),
    ("BODI", "BODI", None, "BODI", "stock", "USD", False),
    ("BODY", "BODY", None, "BODY", "stock", "USD", False),
    ("CBOE", "CBOE", None, "CBOE", "stock", "USD", False),
    ("CCC", "CCC", None, "CCC", "stock", "USD", False),
    ("CCCS", "CCCS", None, "CCCS", "stock", "USD", False),
    ("CCO", "CCO", None, "CCO", "stock", "USD", False),
    ("CDE", "CDE", None, "CDE", "stock", "USD", False),
    ("CDEV", "CDEV", None, "CDEV", "stock", "USD", False),
    ("CLNE", "CLNE", None, "CLNE", "stock", "USD", False),
    ("CLOV", "CLOV", None, "CLOV", "stock", "USD", False),
    ("CNDT", "CNDT", None, "CNDT", "stock", "USD", False),
    ("COTY", "COTY", None, "COTY", "stock", "USD", False),
    ("CRK", "CRK", None, "CRK", "stock", "USD", False),
    ("DRH", "DRH", None, "DRH", "stock", "USD", False),
    ("ENPH", "ENPH", None, "ENPH", "stock", "USD", False),
    ("EVGO", "EVGO", None, "EVGO", "stock", "USD", False),
    ("EVLV", "EVLV", None, "EVLV", "stock", "USD", False),
    ("FAX", "FAX", None, "FAX", "stock", "USD", False),
    ("FCEL", "FCEL", None, "FCEL", "stock", "USD", False),
    ("FINV", "FINV", None, "FINV", "stock", "USD", False),
    ("GAB", "GAB", None, "GAB", "stock", "USD", False),
    ("GEO", "GEO", None, "GEO", "stock", "USD", False),
    ("GNW", "GNW", None, "GNW", "stock", "USD", False),
    ("GOCO", "GOCO", None, "GOCO", "stock", "USD", False),
    ("HIPO", "HIPO", None, "HIPO", "stock", "USD", False),
    ("HL", "HL", None, "HL", "stock", "USD", False),
    ("IBRX", "IBRX", None, "IBRX", "stock", "USD", False),
    ("IGR", "IGR", None, "IGR", "stock", "USD", False),
    ("INDI", "INDI", None, "INDI", "stock", "USD", False),
    ("INO", "INO", None, "INO", "stock", "USD", False),
    ("MANU", "MANU", None, "MANU", "stock", "USD", False),
    ("MFA", "MFA", None, "MFA", "stock", "USD", False),
    ("MKTW", "MKTW", None, "MKTW", "stock", "USD", False),
    ("MNKD", "MNKD", None, "MNKD", "stock", "USD", False),
    ("MNTK", "MNTK", None, "MNTK", "stock", "USD", False),
    ("MVST", "MVST", None, "MVST", "stock", "USD", False),
    ("NRZ", "NRZ", None, "NRZ", "stock", "USD", False),
    ("NUVB", "NUVB", None, "NUVB", "stock", "USD", False),
    ("NYMT", "NYMT", None, "NYMT", "stock", "USD", False),
    ("OCGN", "OCGN", None, "OCGN", "stock", "USD", False),
    ("OCSL", "OCSL", None, "OCSL", "stock", "USD", False),
    ("OPK", "OPK", None, "OPK", "stock", "USD", False),
    ("OUST", "OUST", None, "OUST", "stock", "USD", False),
    ("PAYO", "PAYO", None, "PAYO", "stock", "USD", False),
    ("PBI", "PBI", None, "PBI", "stock", "USD", False),
    ("PGEN", "PGEN", None, "PGEN", "stock", "USD", False),
    ("PKI", "PKI", None, "PKI", "stock", "USD", False),
    ("PSEC", "PSEC", None, "PSEC", "stock", "USD", False),
    ("PTEN", "PTEN", None, "PTEN", "stock", "USD", False),
    ("QSI", "QSI", None, "QSI", "stock", "USD", False),
    ("ROOT", "ROOT", None, "ROOT", "stock", "USD", False),
    ("SENS", "SENS", None, "SENS", "stock", "USD", False),
    ("SGMO", "SGMO", None, "SGMO", "stock", "USD", False),
    ("SIRI", "SIRI", None, "SIRI", "stock", "USD", False),
    ("SMFR", "SMFR", None, "SMFR", "stock", "USD", False),
    ("SQ", "SQ", None, "SQ", "stock", "USD", False),
    ("TDOC", "TDOC", None, "TDOC", "stock", "USD", False),
    ("TWO", "TWO", None, "TWO", "stock", "USD", False),
    ("UA", "UA", None, "UA", "stock", "USD", False),
    ("USA", "USA", None, "USA", "stock", "USD", False),
    ("WGS", "WGS", None, "WGS", "stock", "USD", False),
    ("WISH", "WISH", None, "WISH", "stock", "USD", False),
    ("WKHS", "WKHS", None, "WKHS", "stock", "USD", False),
    ("WMT", "WMT", None, "WMT", "stock", "USD", False),
    ("EDF", "EDF", None, "EDF", "stock", "USD", False),
    ("IDCB", "IDCB", None, "IDCB", "stock", "USD", False),
    ("ITX", "ITX", None, "ITX", "stock", "USD", False),
    ("JWN", "JWN", None, "JWN", "stock", "USD", False),
    ("LNVG", "LNVG", None, "LNVG", "stock", "USD", False),
    ("LTM", "LTM", None, "LATAM Airlines", "stock", "USD", False),
    ("MNTV", "MNTV", None, "MNTV", "stock", "USD", False),
    ("SAVE", "SAVE", None, "SAVE", "stock", "USD", False),
    ("SK", "SK", None, "SK", "stock", "USD", False),
    ("TCTZ", "TCTZ", None, "TCTZ", "stock", "USD", False),
    ("TTE", "TTE", None, "TTE", "stock", "USD", False),
    ("YNDX", "YNDX", None, "YNDX", "stock", "USD", False),
    ("Adidas", "ADS.DE", None, "Adidas AG", "stock", "EUR", False),
    ("Adobe", "ADBE", None, "Adobe Inc.", "stock", "USD", False),
    ("Alcoa", "AA", None, "Alcoa Corp.", "stock", "USD", False),
    ("Alibaba", "BABA", None, "Alibaba Group", "stock", "USD", False),
    ("Amazon", "AMZN", None, "Amazon.com Inc.", "stock", "USD", False),
    ("American_Express", "AXP", None, "American Express", "stock", "USD", False),
    ("Apple", "AAPL", None, "Apple Inc.", "stock", "USD", False),
    ("AT&T", "T", None, "AT&T Inc.", "stock", "USD", False),
    ("Baidu", "BIDU", None, "Baidu Inc.", "stock", "USD", False),
    ("Banco_Santander", "SAN", None, "Banco Santander", "stock", "USD", False),
    ("Bank_of_America", "BAC", None, "Bank of America", "stock", "USD", False),
    ("Bayer", "BAYN.DE", None, "Bayer AG", "stock", "EUR", False),
    ("Boeing", "BA", None, "Boeing Co.", "stock", "USD", False),
    ("Caterpillar", "CAT", None, "Caterpillar Inc.", "stock", "USD", False),
    ("Cisco", "CSCO", None, "Cisco Systems", "stock", "USD", False),
    ("Citigroup", "C", None, "Citigroup Inc.", "stock", "USD", False),
    ("Coca–Cola", "KO", None, "Coca-Cola Co.", "stock", "USD", False),
    ("Deutsche_Bank", "DBK.DE", None, "Deutsche Bank AG", "stock", "EUR", False),
    ("Disney", "DIS", None, "Walt Disney Co.", "stock", "USD", False),
    ("eBay", "EBAY", None, "eBay Inc.", "stock", "USD", False),
    ("Estee_Lauder", "EL", None, "Estee Lauder", "stock", "USD", False),
    ("Ethan_Allen", "ETD", None, "Ethan Allen", "stock", "USD", False),
    ("Exxon", "XOM", None, "Exxon Mobil", "stock", "USD", False),
    ("Ferrari", "RACE", None, "Ferrari NV", "stock", "USD", False),
    ("Ford", "F", None, "Ford Motor Co.", "stock", "USD", False),
    ("General_Electrics", "GE", None, "General Electric", "stock", "USD", False),
    ("Goldman_Sachs", "GS", None, "Goldman Sachs", "stock", "USD", False),
    ("Google", "GOOGL", None, "Alphabet Inc. Class A", "stock", "USD", False),
    ("Harley_Davidson", "HOG", None, "Harley-Davidson", "stock", "USD", False),
    ("Hewlett_Packard", "HPQ", None, "HP Inc.", "stock", "USD", False),
    ("Home_Depot", "HD", None, "Home Depot Inc.", "stock", "USD", False),
    ("Intel", "INTC", None, "Intel Corp.", "stock", "USD", False),
    ("JPMorgan", "JPM", None, "JPMorgan Chase", "stock", "USD", False),
    ("Mastercard", "MA", None, "Mastercard Inc.", "stock", "USD", False),
    ("McDonald", "MCD", None, "McDonald's Corp.", "stock", "USD", False),
    ("Microsoft", "MSFT", None, "Microsoft Corp.", "stock", "USD", False),
    ("Nike", "NKE", None, "Nike Inc.", "stock", "USD", False),
    ("nVidia", "NVDA", None, "NVIDIA Corp.", "stock", "USD", False),
    ("Oracle", "ORCL", None, "Oracle Corp.", "stock", "USD", False),
    ("Petrobras", "PBR", None, "Petrobras SA", "stock", "USD", False),
    ("Pfizer", "PFE", None, "Pfizer Inc.", "stock", "USD", False),
    ("Philip_Morris", "PM", None, "Philip Morris", "stock", "USD", False),
    ("Procter&Gamble", "PG", None, "Procter & Gamble", "stock", "USD", False),
    ("Ralph_Lauren", "RL", None, "Ralph Lauren Corp.", "stock", "USD", False),
    ("Salesforce", "CRM", None, "Salesforce Inc.", "stock", "USD", False),
    ("Snap", "SNAP", None, "Snap Inc.", "stock", "USD", False),
    ("Starbucks", "SBUX", None, "Starbucks Corp.", "stock", "USD", False),
    ("Tesla", "TSLA", None, "Tesla Inc.", "stock", "USD", False),
    ("Travelers", "TRV", None, "Travelers Companies", "stock", "USD", False),
    ("TripAdvisor", "TRIP", None, "Tripadvisor Inc.", "stock", "USD", False),
    ("UnitedHealth", "UNH", None, "UnitedHealth Group", "stock", "USD", False),
    ("Vale", "VALE", None, "Vale SA", "stock", "USD", False),
    ("Verizon", "VZ", None, "Verizon Communications", "stock", "USD", False),
    ("VF", "VFC", None, "VF Corporation", "stock", "USD", False),
    ("Visa", "V", None, "Visa Inc.", "stock", "USD", False),
    ("Vodafone", "VOD", None, "Vodafone Group", "stock", "USD", False),
    ("Volkswagen", "VOW3.DE", None, "Volkswagen AG", "stock", "EUR", False),
    ("Wells_Fargo", "WFC", None, "Wells Fargo & Co.", "stock", "USD", False),
    ("Williams_Sonoma", "WSM", None, "Williams-Sonoma", "stock", "USD", False),
    ("Yandex", "YNDX", None, "Yandex NV", "stock", "USD", False),
    # ---------- ETF (34) ----------
    ("AGG", "AGG", None, "iShares Core US Aggregate Bond ETF", "etf", "USD", False),
    ("BITB", "BITB", None, "BITB", "etf", "USD", False),
    ("BRRR", "BRRR", None, "BRRR", "etf", "USD", False),
    ("BTCO", "BTCO", None, "BTCO", "etf", "USD", False),
    ("BTCW", "BTCW", None, "BTCW", "etf", "USD", False),
    ("CETH", "CETH", None, "CETH", "etf", "USD", False),
    ("DEFI", "DEFI", None, "DEFI", "etf", "USD", False),
    ("ETHA", "ETHA", None, "ETHA", "etf", "USD", False),
    ("ETHE", "ETHE", None, "ETHE", "etf", "USD", False),
    ("EWG", "EWG", None, "iShares MSCI Germany ETF", "etf", "USD", False),
    ("EWU", "EWU", None, "iShares MSCI United Kingdom ETF", "etf", "USD", False),
    ("EWW", "EWW", None, "iShares MSCI Mexico ETF", "etf", "USD", False),
    ("EWZ", "EWZ", None, "iShares MSCI Brazil ETF", "etf", "USD", False),
    ("EZBC", "EZBC", None, "EZBC", "etf", "USD", False),
    ("FBTC", "FBTC", None, "FBTC", "etf", "USD", False),
    ("FETH", "FETH", None, "FETH", "etf", "USD", False),
    ("FXI", "FXI", None, "iShares China Large-Cap ETF", "etf", "USD", False),
    ("HODL", "HODL", None, "HODL", "etf", "USD", False),
    ("IBIT", "IBIT", None, "IBIT", "etf", "USD", False),
    ("IJH", "IJH", None, "IJH", "etf", "USD", False),
    ("ILF", "ILF", None, "iShares Latin America 40 ETF", "etf", "USD", False),
    ("SPY", "SPY", None, "SPDR S&P 500 ETF", "etf", "USD", False),
    ("TETH", "TETH", None, "TETH", "etf", "USD", False),
    ("VGK", "VGK", None, "Vanguard FTSE Europe ETF", "etf", "USD", False),
    ("BITO", "BITO", None, "BITO", "etf", "USD", False),
    ("BND", "BND", None, "BND", "etf", "USD", False),
    ("IWM", "IWM", None, "IWM", "etf", "USD", False),
    ("QQQ", "QQQ", None, "QQQ", "etf", "USD", False),
    ("TQQQ", "TQQQ", None, "TQQQ", "etf", "USD", False),
    ("VTI", "VTI", None, "VTI", "etf", "USD", False),
    ("VTV", "VTV", None, "VTV", "etf", "USD", False),
    ("XLE", "XLE", None, "XLE", "etf", "USD", False),
    ("XLF", "XLF", None, "XLF", "etf", "USD", False),
    ("XLV", "XLV", None, "XLV", "etf", "USD", False),
    # ---------- BOND (3) ----------
    ("IEF", "IEF", None, "iShares 7-10 Year Treasury Bond ETF", "bond", "USD", False),
    ("SHY", "SHY", None, "iShares 1-3 Year Treasury Bond ETF", "bond", "USD", False),
    ("TLT", "TLT", None, "iShares 20+ Year Treasury Bond ETF", "bond", "USD", False),
    # ---------- INDEX (19) ----------
    ("ES", "^GSPC", None, "S&P 500", "index", "USD", False),
    ("ESCash", "^GSPC", None, "S&P 500 (cash)", "index", "USD", False),
    ("FCE", "^FCHI", None, "CAC 40 (France)", "index", "USD", False),
    ("FDAX", "^GDAXI", None, "DAX 40 (Germany)", "index", "USD", False),
    ("FDAXCash", "^GDAXI", None, "DAX 40 cash", "index", "USD", False),
    ("FESX", "^STOXX50E", None, "Euro Stoxx 50", "index", "USD", False),
    ("FTI", "^AEX", None, "AEX 25 (Netherlands)", "index", "USD", False),
    ("HSI", "^HSI", None, "Hang Seng (Hong Kong)", "index", "USD", False),
    ("NIY", "^N225", None, "Nikkei 225", "index", "USD", False),
    ("NIYCash", "^N225", None, "Nikkei 225 cash", "index", "USD", False),
    ("NQ", "^NDX", None, "Nasdaq 100", "index", "USD", False),
    ("NQCash", "^NDX", None, "Nasdaq 100 cash", "index", "USD", False),
    ("TF", "^RUT", None, "Russell 2000", "index", "USD", False),
    ("USDX", "DX-Y.NYB", None, "US Dollar Index", "index", "USD", False),
    ("VIX", "^VIX", None, "CBOE Volatility Index", "index", "USD", False),
    ("YM", "^DJI", None, "Dow Jones Industrial", "index", "USD", False),
    ("YMCash", "^DJI", None, "Dow Jones cash", "index", "USD", False),
    ("Z", "^FTSE", None, "FTSE 100 (UK)", "index", "USD", False),
    ("ZCash", "^FTSE", None, "FTSE 100 cash", "index", "USD", False),
    # ---------- COMMODITY (20) ----------
    ("BRN", "BZ=F", None, "Brent Crude Oil", "commodity", "USD", False),
    ("BRNCash", "BZ=F", None, "Brent Crude (cash)", "commodity", "USD", False),
    ("CL", "CL=F", None, "WTI Crude Oil", "commodity", "USD", False),
    ("HO", "HO=F", None, "Heating Oil", "commodity", "USD", False),
    ("NG", "NG=F", None, "Natural Gas", "commodity", "USD", False),
    ("NGASCash", "NG=F", None, "Natural Gas (cash)", "commodity", "USD", False),
    ("USOILCash", "CL=F", None, "WTI Crude (cash)", "commodity", "USD", False),
    ("HG", "HG=F", None, "Copper Futures", "commodity", "USD", False),
    ("PA", "PA=F", None, "Palladium Futures", "commodity", "USD", False),
    ("PL", "PL=F", None, "Platinum Futures", "commodity", "USD", False),
    ("XAGUSD", "SI=F", None, "Silver", "commodity", "USD", False),
    ("XAUUSD", "GC=F", None, "Gold", "commodity", "USD", False),
    ("COCOA", "CC=F", None, "Cocoa Futures", "commodity", "USD", False),
    ("COFFEE", "KC=F", None, "Coffee Futures", "commodity", "USD", False),
    ("CORN", "ZC=F", None, "Corn Futures", "commodity", "USD", False),
    ("COTTON", "CT=F", None, "Cotton Futures", "commodity", "USD", False),
    ("SOYBEAN", "ZS=F", None, "Soybean Futures", "commodity", "USD", False),
    ("SUGAR", "SB=F", None, "Sugar Futures", "commodity", "USD", False),
    ("WHEAT", "ZW=F", None, "Wheat Futures", "commodity", "USD", False),
    ("iXAU", "GC=F", None, "Gold (swap-free)", "commodity", "USD", False),
    # ---------- FX (50) ----------
    ("AUDCAD", "AUDCAD=X", "FX:AUDCAD", "AUD/CAD cross", "fx", "CAD", False),
    ("AUDCHF", "AUDCHF=X", "FX:AUDCHF", "AUD/CHF cross", "fx", "CHF", False),
    ("AUDJPY", "AUDJPY=X", "FX:AUDJPY", "AUD/JPY cross", "fx", "JPY", False),
    ("AUDNZD", "AUDNZD=X", "FX:AUDNZD", "AUD/NZD cross", "fx", "NZD", False),
    ("AUDUSD", "AUDUSD=X", "FX:AUDUSD", "AUD/USD cross", "fx", "USD", False),
    ("CADCHF", "CADCHF=X", "FX:CADCHF", "CAD/CHF cross", "fx", "CHF", False),
    ("CADJPY", "CADJPY=X", "FX:CADJPY", "CAD/JPY cross", "fx", "JPY", False),
    ("CHFJPY", "CHFJPY=X", "FX:CHFJPY", "CHF/JPY cross", "fx", "JPY", False),
    ("CHFSGD", "CHFSGD=X", "FX:CHFSGD", "CHF/SGD cross", "fx", "SGD", False),
    ("EURAUD", "EURAUD=X", "FX:EURAUD", "EUR/AUD cross", "fx", "AUD", False),
    ("EURCAD", "EURCAD=X", "FX:EURCAD", "EUR/CAD cross", "fx", "CAD", False),
    ("EURCHF", "EURCHF=X", "FX:EURCHF", "EUR/CHF cross", "fx", "CHF", False),
    ("EURCNH", "EURCNH=X", "FX:EURCNH", "EUR/CNH cross", "fx", "CNH", False),
    ("EURGBP", "EURGBP=X", "FX:EURGBP", "EUR/GBP cross", "fx", "GBP", False),
    ("EURJPY", "EURJPY=X", "FX:EURJPY", "EUR/JPY cross", "fx", "JPY", False),
    ("EURMXN", "EURMXN=X", "FX:EURMXN", "EUR/MXN cross", "fx", "MXN", False),
    ("EURNOK", "EURNOK=X", "FX:EURNOK", "EUR/NOK cross", "fx", "NOK", False),
    ("EURNZD", "EURNZD=X", "FX:EURNZD", "EUR/NZD cross", "fx", "NZD", False),
    ("EURPLN", "EURPLN=X", "FX:EURPLN", "EUR/PLN cross", "fx", "PLN", False),
    ("EURSEK", "EURSEK=X", "FX:EURSEK", "EUR/SEK cross", "fx", "SEK", False),
    ("EURSGD", "EURSGD=X", "FX:EURSGD", "EUR/SGD cross", "fx", "SGD", False),
    ("EURUSD", "EURUSD=X", "FX:EURUSD", "EUR/USD cross", "fx", "USD", False),
    ("GBPAUD", "GBPAUD=X", "FX:GBPAUD", "GBP/AUD cross", "fx", "AUD", False),
    ("GBPCAD", "GBPCAD=X", "FX:GBPCAD", "GBP/CAD cross", "fx", "CAD", False),
    ("GBPCHF", "GBPCHF=X", "FX:GBPCHF", "GBP/CHF cross", "fx", "CHF", False),
    ("GBPJPY", "GBPJPY=X", "FX:GBPJPY", "GBP/JPY cross", "fx", "JPY", False),
    ("GBPNZD", "GBPNZD=X", "FX:GBPNZD", "GBP/NZD cross", "fx", "NZD", False),
    ("GBPSEK", "GBPSEK=X", "FX:GBPSEK", "GBP/SEK cross", "fx", "SEK", False),
    ("GBPUSD", "GBPUSD=X", "FX:GBPUSD", "GBP/USD cross", "fx", "USD", False),
    ("NOKJPY", "NOKJPY=X", "FX:NOKJPY", "NOK/JPY cross", "fx", "JPY", False),
    ("NZDCAD", "NZDCAD=X", "FX:NZDCAD", "NZD/CAD cross", "fx", "CAD", False),
    ("NZDCHF", "NZDCHF=X", "FX:NZDCHF", "NZD/CHF cross", "fx", "CHF", False),
    ("NZDJPY", "NZDJPY=X", "FX:NZDJPY", "NZD/JPY cross", "fx", "JPY", False),
    ("NZDUSD", "NZDUSD=X", "FX:NZDUSD", "NZD/USD cross", "fx", "USD", False),
    ("SGDJPY", "SGDJPY=X", "FX:SGDJPY", "SGD/JPY cross", "fx", "JPY", False),
    ("USDCAD", "USDCAD=X", "FX:USDCAD", "USD/CAD cross", "fx", "CAD", False),
    ("USDCHF", "USDCHF=X", "FX:USDCHF", "USD/CHF cross", "fx", "CHF", False),
    ("USDCLP", "USDCLP=X", "FX:USDCLP", "USD/CLP cross", "fx", "CLP", False),
    ("USDCNH", "USDCNH=X", "FX:USDCNH", "USD/CNH cross", "fx", "CNH", False),
    ("USDDKK", "USDDKK=X", "FX:USDDKK", "USD/DKK cross", "fx", "DKK", False),
    ("USDJPY", "USDJPY=X", "FX:USDJPY", "USD/JPY cross", "fx", "JPY", False),
    ("USDMXN", "USDMXN=X", "FX:USDMXN", "USD/MXN cross", "fx", "MXN", False),
    ("USDNOK", "USDNOK=X", "FX:USDNOK", "USD/NOK cross", "fx", "NOK", False),
    ("USDPLN", "USDPLN=X", "FX:USDPLN", "USD/PLN cross", "fx", "PLN", False),
    ("USDRUB", "USDRUB=X", "FX:USDRUB", "USD/RUB cross", "fx", "RUB", False),
    ("USDSEK", "USDSEK=X", "FX:USDSEK", "USD/SEK cross", "fx", "SEK", False),
    ("USDSGD", "USDSGD=X", "FX:USDSGD", "USD/SGD cross", "fx", "SGD", False),
    ("EURTRY", "EURTRY=X", "FX:EURTRY", "EUR/TRY cross", "fx", "TRY", False),
    ("USDTRY", "USDTRY=X", "FX:USDTRY", "USD/TRY cross", "fx", "TRY", False),
    ("USDZAR", "USDZAR=X", "FX:USDZAR", "USD/ZAR cross", "fx", "ZAR", False),
    # ---------- CRYPTO (109) ----------
    ("AAVEUSD", "AAVE-USD", "BINANCE:AAVEUSDT", "AAVE", "crypto", "USD", True),
    ("ACTUSD", "ACT-USD", "BINANCE:ACTUSDT", "ACT", "crypto", "USD", True),
    ("ADAUSD", "ADA-USD", "BINANCE:ADAUSDT", "Cardano", "crypto", "USD", True),
    ("AEROUSD", "AERO-USD", "BINANCE:AEROUSDT", "AERO", "crypto", "USD", True),
    ("ALGOUSD", "ALGO-USD", "BINANCE:ALGOUSDT", "ALGO", "crypto", "USD", True),
    ("APEUSD", "APE-USD", "BINANCE:APEUSDT", "ApeCoin", "crypto", "USD", True),
    ("APTUSD", "APT-USD", "BINANCE:APTUSDT", "APT", "crypto", "USD", True),
    ("ARBUSD", "ARB-USD", "BINANCE:ARBUSDT", "ARB", "crypto", "USD", True),
    ("ASTERUSD", "ASTER-USD", "BINANCE:ASTERUSDT", "ASTER", "crypto", "USD", True),
    ("ASTRUSD", "ASTR-USD", "BINANCE:ASTRUSDT", "ASTR", "crypto", "USD", True),
    ("ATMUSD", "ATOM-USD", "BINANCE:ATMUSDT", "Cosmos", "crypto", "USD", True),
    ("AVAXUSD", "AVAX-USD", "BINANCE:AVAXUSDT", "AVAX", "crypto", "USD", True),
    ("AXSUSD", "AXS-USD", "BINANCE:AXSUSDT", "AXS", "crypto", "USD", True),
    ("BCHUSD", "BCH-USD", "BINANCE:BCHUSDT", "Bitcoin Cash", "crypto", "USD", True),
    ("BLASTUSD", "BLAST-USD", "BINANCE:BLASTUSDT", "BLAST", "crypto", "USD", True),
    ("BNBUSD", "BNB-USD", "BINANCE:BNBUSDT", "BNB", "crypto", "USD", True),
    ("BOMEUSD", "BOME-USD", "BINANCE:BOMEUSDT", "BOME", "crypto", "USD", True),
    ("BONKUSD", "BONK-USD", "BINANCE:BONKUSDT", "BONK", "crypto", "USD", True),
    ("BRETTUSD", "BRETT-USD", "BINANCE:BRETTUSDT", "BRETT", "crypto", "USD", True),
    ("BTCUSD", "BTC-USD", "BINANCE:BTCUSDT", "Bitcoin", "crypto", "USD", True),
    ("CAKEUSD", "CAKE-USD", "BINANCE:CAKEUSDT", "CAKE", "crypto", "USD", True),
    ("CHZUSD", "CHZ-USD", "BINANCE:CHZUSDT", "CHZ", "crypto", "USD", True),
    ("COMPUSD", "COMP-USD", "BINANCE:COMPUSDT", "COMP", "crypto", "USD", True),
    ("DASHUSD", "DASH-USD", "BINANCE:DASHUSDT", "DASH", "crypto", "USD", True),
    ("DOGEUSD", "DOGE-USD", "BINANCE:DOGEUSDT", "DOGE", "crypto", "USD", True),
    ("DOTUSD", "DOT-USD", "BINANCE:DOTUSDT", "Polkadot", "crypto", "USD", True),
    ("DYMUSD", "DYM-USD", "BINANCE:DYMUSDT", "DYM", "crypto", "USD", True),
    ("EGLDUSD", "EGLD-USD", "BINANCE:EGLDUSDT", "EGLD", "crypto", "USD", True),
    ("ENJUSD", "ENJ-USD", "BINANCE:ENJUSDT", "ENJ", "crypto", "USD", True),
    ("ETCUSD", "ETC-USD", "BINANCE:ETCUSDT", "Ethereum Classic", "crypto", "USD", True),
    ("ETHUSD", "ETH-USD", "BINANCE:ETHUSDT", "Ethereum", "crypto", "USD", True),
    ("FILUSD", "FIL-USD", "BINANCE:FILUSDT", "FIL", "crypto", "USD", True),
    ("FLOKIUSD", "FLOKI-USD", "BINANCE:FLOKIUSDT", "FLOKI", "crypto", "USD", True),
    ("FTMUSD", "FTM-USD", "BINANCE:FTMUSDT", "FTM", "crypto", "USD", True),
    ("GIGAUSD", "GIGA-USD", "BINANCE:GIGAUSDT", "GIGA", "crypto", "USD", True),
    ("GMTUSD", "GMT-USD", "BINANCE:GMTUSDT", "STEPN", "crypto", "USD", True),
    ("GOATUSD", "GOAT-USD", "BINANCE:GOATUSDT", "GOAT", "crypto", "USD", True),
    ("GRTUSD", "GRT-USD", "BINANCE:GRTUSDT", "GRT", "crypto", "USD", True),
    ("HBARUSD", "HBAR-USD", "BINANCE:HBARUSDT", "HBAR", "crypto", "USD", True),
    ("HYPEUSD", "HYPE-USD", "BINANCE:HYPEUSDT", "HYPE", "crypto", "USD", True),
    ("ICPUSD", "ICP-USD", "BINANCE:ICPUSDT", "Internet Computer", "crypto", "USD", True),
    ("IMXUSD", "IMX-USD", "BINANCE:IMXUSDT", "IMX", "crypto", "USD", True),
    ("INJUSD", "INJ-USD", "BINANCE:INJUSDT", "INJ", "crypto", "USD", True),
    ("IOTUSD", "IOTA-USD", "BINANCE:IOTUSDT", "IOTA", "crypto", "USD", True),
    ("JUPUSD", "JUP-USD", "BINANCE:JUPUSDT", "JUP", "crypto", "USD", True),
    ("LDOUSD", "LDO-USD", "BINANCE:LDOUSDT", "LDO", "crypto", "USD", True),
    ("LNKUSD", "LINK-USD", "BINANCE:LNKUSDT", "Chainlink", "crypto", "USD", True),
    ("LTCUSD", "LTC-USD", "BINANCE:LTCUSDT", "Litecoin", "crypto", "USD", True),
    ("MANAUSD", "MANA-USD", "BINANCE:MANAUSDT", "MANA", "crypto", "USD", True),
    ("MEWUSD", "MEW-USD", "BINANCE:MEWUSDT", "MEW", "crypto", "USD", True),
    ("MINAUSD", "MINA-USD", "BINANCE:MINAUSDT", "MINA", "crypto", "USD", True),
    ("MOGUSD", "MOG-USD", "BINANCE:MOGUSDT", "MOG", "crypto", "USD", True),
    ("NEARUSD", "NEAR-USD", "BINANCE:NEARUSDT", "NEAR", "crypto", "USD", True),
    ("NEOUSD", "NEO-USD", "BINANCE:NEOUSDT", "Neo", "crypto", "USD", True),
    ("ONTUSD", "ONT-USD", "BINANCE:ONTUSDT", "Ontology", "crypto", "USD", True),
    ("OPUSD", "OP-USD", "BINANCE:OPUSDT", "OP", "crypto", "USD", True),
    ("PENGUUSD", "PENGU-USD", "BINANCE:PENGUUSDT", "PENGU", "crypto", "USD", True),
    ("PEPEUSD", "PEPE24478-USD", "BINANCE:PEPEUSDT", "Pepe", "crypto", "USD", True),
    ("PNUTUSD", "PNUT-USD", "BINANCE:PNUTUSDT", "PNUT", "crypto", "USD", True),
    ("POLUSD", "POL-USD", "BINANCE:POLUSDT", "POL", "crypto", "USD", True),
    ("PONKEUSD", "PONKE-USD", "BINANCE:PONKEUSDT", "PONKE", "crypto", "USD", True),
    ("QNTUSD", "QNT-USD", "BINANCE:QNTUSDT", "QNT", "crypto", "USD", True),
    ("QTMUSD", "QTUM-USD", "BINANCE:QTMUSDT", "Qtum", "crypto", "USD", True),
    ("RNDRUSD", "RNDR-USD", "BINANCE:RNDRUSDT", "RNDR", "crypto", "USD", True),
    ("ROSEUSD", "ROSE-USD", "BINANCE:ROSEUSDT", "ROSE", "crypto", "USD", True),
    ("RUNEUSD", "RUNE-USD", "BINANCE:RUNEUSDT", "RUNE", "crypto", "USD", True),
    ("SANDUSD", "SAND-USD", "BINANCE:SANDUSDT", "SAND", "crypto", "USD", True),
    ("SHIBUSD", "SHIB-USD", "BINANCE:SHIBUSDT", "SHIB", "crypto", "USD", True),
    ("SNXUSD", "SNX-USD", "BINANCE:SNXUSDT", "Synthetix", "crypto", "USD", True),
    ("SOLUSD", "SOL-USD", "BINANCE:SOLUSDT", "Solana", "crypto", "USD", True),
    ("SPXUSD", "SPX-USD", "BINANCE:SPXUSDT", "SPX", "crypto", "USD", True),
    ("STXUSD", "STX-USD", "BINANCE:STXUSDT", "STX", "crypto", "USD", True),
    ("SUIUSD", "SUI-USD", "BINANCE:SUIUSDT", "SUI", "crypto", "USD", True),
    ("SUSHIUSD", "SUSHI-USD", "BINANCE:SUSHIUSDT", "SUSHI", "crypto", "USD", True),
    ("TAOUSD", "TAO-USD", "BINANCE:TAOUSDT", "TAO", "crypto", "USD", True),
    ("THETAUSD", "THETA-USD", "BINANCE:THETAUSDT", "THETA", "crypto", "USD", True),
    ("TIAUSD", "TIA-USD", "BINANCE:TIAUSDT", "TIA", "crypto", "USD", True),
    ("TONUSD", "TON11419-USD", "BINANCE:TONUSDT", "Toncoin", "crypto", "USD", True),
    ("TRUMPUSD", "TRUMP-USD", "BINANCE:TRUMPUSDT", "TRUMP", "crypto", "USD", True),
    ("TRXUSD", "TRX-USD", "BINANCE:TRXUSDT", "TRON", "crypto", "USD", True),
    ("TURBOUSD", "TURBO-USD", "BINANCE:TURBOUSDT", "TURBO", "crypto", "USD", True),
    ("TWTUSD", "TWT-USD", "BINANCE:TWTUSDT", "TWT", "crypto", "USD", True),
    ("UMAUSD", "UMA-USD", "BINANCE:UMAUSDT", "UMA", "crypto", "USD", True),
    ("UNIUSD", "UNI7083-USD", "BINANCE:UNIUSDT", "Uniswap", "crypto", "USD", True),
    ("VETUSD", "VET-USD", "BINANCE:VETUSDT", "VeChain", "crypto", "USD", True),
    ("WIFUSD", "WIF-USD", "BINANCE:WIFUSDT", "WIF", "crypto", "USD", True),
    ("WLDUSD", "WLD-USD", "BINANCE:WLDUSDT", "WLD", "crypto", "USD", True),
    ("WLFIUSD", "WLFI-USD", "BINANCE:WLFIUSDT", "WLFI", "crypto", "USD", True),
    ("XLMUSD", "XLM-USD", "BINANCE:XLMUSDT", "Stellar", "crypto", "USD", True),
    ("XMRUSD", "XMR-USD", "BINANCE:XMRUSDT", "Monero", "crypto", "USD", True),
    ("XRPUSD", "XRP-USD", "BINANCE:XRPUSDT", "Ripple", "crypto", "USD", True),
    ("XTZUSD", "XTZ-USD", "BINANCE:XTZUSDT", "Tezos", "crypto", "USD", True),
    ("ZECUSD", "ZEC-USD", "BINANCE:ZECUSDT", "Zcash", "crypto", "USD", True),
    ("ZKUSD", "ZK-USD", "BINANCE:ZKUSDT", "ZK", "crypto", "USD", True),
    ("ZROUSD", "ZRO-USD", "BINANCE:ZROUSDT", "ZRO", "crypto", "USD", True),
    ("ZRXUSD", "ZRX-USD", "BINANCE:ZRXUSDT", "0x", "crypto", "USD", True),
    ("iBTCUSD", "BTC-USD", None, "Bitcoin (swap-free)", "crypto", "USD", True),
    ("iETHUSD", "ETH-USD", None, "Ethereum (swap-free)", "crypto", "USD", True),
    ("iXRPUSD", "XRP-USD", None, "Ripple (swap-free)", "crypto", "USD", True),
    ("BTGUSD", "BTG-USD", "BINANCE:BTGUSDT", "BTG", "crypto", "USD", True),
    ("CMPUSD", "COMP-USD", "BINANCE:CMPUSDT", "Compound", "crypto", "USD", True),
    ("DOGUSD", "DOGE-USD", "BINANCE:DOGUSDT", "Dogecoin", "crypto", "USD", True),
    ("DSHUSD", "DASH-USD", "BINANCE:DSHUSDT", "Dash", "crypto", "USD", True),
    ("MKRUSD", "MKR-USD", "BINANCE:MKRUSDT", "MKR", "crypto", "USD", True),
    ("MTCUSD", "MTC-USD", "BINANCE:MTCUSDT", "MTC", "crypto", "USD", True),
    ("NOTUSD", "NOT-USD", "BINANCE:NOTUSDT", "NOT", "crypto", "USD", True),
    ("OMGUSD", "OMG-USD", "BINANCE:OMGUSDT", "OMG", "crypto", "USD", True),
    ("SBAUSD", "SHIB-USD", "BINANCE:SBAUSDT", "Shiba Inu", "crypto", "USD", True),
    ("XEMUSD", "XEM-USD", "BINANCE:XEMUSDT", "XEM", "crypto", "USD", True),
]
